// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionId, ConnectionSettings, Engine, FolderColor, FolderId, FolderTree, Kubeconfigs, ManagedInstance, Preferences } from "./config";
import type { ConnectionState } from "./engine";
import type { CarriedSecrets } from "./transfert";

/**
 * L'issue de `load_config` en v7 — celle d'aujourd'hui, l'arbre à la place des projets, **plus un
 * cinquième cas**.
 */
export type ConfigLoad = { "kind": "fresh" } | { "kind": "loaded", tree: FolderTree, preferences: Preferences, instances: Array<ManagedInstance>, kubeconfigs: Kubeconfigs, } | { "kind": "secretsMigrationFailed", reason: string, } | { "kind": "unreadable", reason: string, quarantinedTo: string, } | { "kind": "tooNew", found: number, supported: number, };

/**
 * Un état de connexion, avec la connexion qu'il concerne — ce que `connection_states` rend.
 *
 * Les entrées d'instance (`instance/<id>`) n'y figurent pas, comme aujourd'hui.
 */
export type ConnectionStateEntry = { key: DatabaseKey, state: ConnectionState, };

/**
 * `create_console`, `save_console`, `rename_console`, `delete_console`.
 */
export type ConsoleRequest = { connection: ConnectionId, name: string, 
/**
 * Le texte, pour l'écriture. Ignoré par les trois autres.
 */
sql: string | null, 
/**
 * Le nouveau nom, pour le renommage.
 */
renameTo: string | null, };

/**
 * `create_folder` : un dossier neuf, nommé « dossier N » — le plus petit N libre parmi ses frères.
 *
 * **Aucune modale ne nomme un objet à sa création** : on le crée, puis on le renomme sur place.
 */
export type CreateFolderRequest = { 
/**
 * `None` : à la racine.
 */
parent: FolderId | null, };

/**
 * Ce que `create_folder` rend : l'arbre, **et l'identifiant du dossier créé**.
 *
 * L'identifiant est tiré par le cœur ; sans lui, l'écran ne saurait pas quelle ligne passer en
 * renommage sur place — deviner « le dernier enfant » cesserait d'être vrai au premier tri.
 */
export type CreateFolderResult = { tree: FolderTree, folder: FolderId, };

/**
 * Ce qui désigne une connexion ouverte, pour les vingt commandes du moteur et le dump : son
 * identifiant, **et rien d'autre**. Le triplet `projet/base/environnement` disparaît.
 *
 * Le cœur en dérive la clé du registre par `cle_de_connexion` ; le front n'a aucune convention à
 * connaître.
 */
export type DatabaseKey = { connection: ConnectionId, };

/**
 * `delete_database`.
 */
export type DeleteDatabaseRequest = { connection: ConnectionId, };

/**
 * `delete_folder` : ferme toutes les connexions du sous-arbre et efface leurs secrets.
 */
export type DeleteFolderRequest = { folder: FolderId, };

/**
 * Ce que rend un retrait — d'un dossier comme d'une connexion.
 */
export type DeleteResult = { tree: FolderTree, 
/**
 * Les connexions retirées : une seule pour `delete_database`, tout le sous-arbre pour
 * `delete_folder`. **C'est ce que l'écran ferme** — onglets, états, cache —, et le lui dire
 * évite qu'il le recalcule sur un arbre qui ne les contient déjà plus.
 */
deletedConnections: Array<ConnectionId>, 
/**
 * Les mots de passe que le magasin n'a pas su effacer.
 */
leftoverSecrets: Array<string>, };

/**
 * La requête d'export ou d'import de dump — celle d'aujourd'hui, désignée par l'identifiant.
 *
 * **`variant.readOnly` n'est plus cru** (#168) : le refus d'importer lit la lecture seule effective
 * dans la configuration, par `key.connection`.
 */
export type DumpRequest = { key: DatabaseKey, variant: ConnectionSettings, engine: Engine, file: string, };

/**
 * `export_projects` : un dossier et son sous-arbre, ou tout l'arbre. Les noms de commande restent
 * ceux d'`API-30`.
 */
export type ExportProjectsRequest = { file: string, 
/**
 * Le dossier à exporter, qui devient un dossier racine du fichier — sa lecture seule et ses
 * libellés hérités **matérialisés**. `None` : tout l'arbre, connexions à la racine comprises.
 */
folder: FolderId | null, includePasswords: boolean, };

/**
 * Ce qu'un export a écrit.
 */
export type ExportReport = { 
/**
 * Les dossiers écrits, à toute profondeur.
 */
folders: number, connections: number, consoles: number, passwordsCarried: number, 
/**
 * Les connexions dont le magasin n'a rien à rendre, par leur chemin (« Atelier Nord › prod ›
 * analytics »).
 */
passwordsMissing: Array<string>, };

/**
 * Le détail de ce qu'une entrée du fichier apporte, et de ce qu'elle n'apporte pas.
 *
 * Les listes d'`ProjectOutcome` gardent leur sens ; les connexions s'y écrivent par leur **chemin**
 * (« Atelier Nord › prod › analytics »), les dossiers aussi.
 */
export type FolderOutcome = { 
/**
 * Le nom du dossier de premier niveau ; `None` pour la ligne « connexions à la racine ».
 */
folder: string | null, verdict: FolderVerdict, 
/**
 * Les dossiers que la fusion crée, à toute profondeur.
 */
foldersAdded: Array<string>, 
/**
 * Les dossiers déjà présents ici (même nom, même place) : **nom et couleur locaux gardés**.
 */
foldersKept: Array<string>, 
/**
 * Les dossiers locaux qui **passent en lecture seule** parce que le fichier la déclare : la
 * lecture seule fusionne en « local OU fichier », jamais affaiblie.
 */
readOnlyFromFile: Array<string>, connectionsAdded: Array<string>, 
/**
 * Les connexions dont l'identifiant existe déjà ici, où que ce soit : réglages et emplacement
 * locaux gardés, consoles versées. Écrites par leur chemin **local**.
 */
connectionsKept: Array<string>, connectionsRejected: Array<string>, consolesAdded: Array<string>, consolesKept: Array<string>, passwordsStored: Array<string>, passwordsMissing: Array<string>, localPaths: Array<string>, valueLabelsAdded: Array<string>, valueLabelsKept: Array<string>, kubeconfigsMissing: Array<string>, };

/**
 * Le sort d'une entrée du fichier.
 */
export type FolderVerdict = { "kind": "created" } | { "kind": "merged" } | { "kind": "skipped" } | { "kind": "rejected", reason: string, };

/**
 * `import_projects`.
 */
export type ImportProjectsRequest = { file: string, selection: ImportSelection | null, };

/**
 * Ce qu'un import rend : l'arbre d'après, et le rapport.
 */
export type ImportProjectsResult = { tree: FolderTree, report: ImportReport, };

/**
 * Ce qu'un import ferait, ou a fait — le même calcul dans les deux cas.
 */
export type ImportReport = { 
/**
 * La version que le fichier déclare ; une antérieure a été migrée à la lecture.
 */
version: number, secrets: CarriedSecrets, 
/**
 * Un sort par dossier de premier niveau du fichier, dans l'ordre du fichier, **puis** une ligne
 * pour les connexions rangées à la racine du fichier s'il en porte (`folder: null`).
 */
folders: Array<FolderOutcome>, };

/**
 * Ce que la modale d'import retient. `None` dans [`ImportProjectsRequest`] retient tout.
 */
export type ImportSelection = { 
/**
 * Les dossiers de premier niveau du fichier retenus, **par nom** — c'est ainsi qu'ils
 * s'apparient.
 */
folders: Array<string>, 
/**
 * Retenir aussi les connexions que le fichier range à la racine.
 */
rootConnections: boolean, };

/**
 * `move_database` : ranger une connexion ailleurs, ou la réordonner. Mêmes règles que
 * [`MoveFolderRequest`] ; ni le registre ni le magasin de secrets ne sont touchés.
 */
export type MoveDatabaseRequest = { connection: ConnectionId, 
/**
 * `None` : à la racine.
 */
folder: FolderId | null, index: number | null, confirmed: boolean, };

/**
 * `move_folder` : ranger un dossier ailleurs, ou le réordonner parmi ses frères.
 *
 * Refusé : le dossier lui-même ou l'un de ses descendants comme destination, un identifiant
 * inconnu, un frère homonyme à l'arrivée (pas de renommage automatique), et une transaction
 * manuelle ouverte sur une connexion dont la lecture seule changerait.
 */
export type MoveFolderRequest = { folder: FolderId, 
/**
 * `None` : à la racine.
 */
parent: FolderId | null, 
/**
 * La place parmi les frères d'arrivée, **le dossier déplacé exclu du compte** ; `None`, ou un
 * rang trop grand : en dernier.
 */
index: number | null, 
/**
 * **Exigé côté cœur** quand le déplacement change la lecture seule effective d'au moins une
 * connexion, dans un sens ou dans l'autre. Faux, la commande rend
 * [`MoveResult::ConfirmationRequired`] et ne déplace rien.
 */
confirmed: boolean, };

/**
 * L'issue d'un déplacement.
 */
export type MoveResult = { "kind": "moved", tree: FolderTree, } | { "kind": "confirmationRequired", 
/**
 * Les connexions qui passeraient en lecture seule.
 */
becomesReadOnly: Array<ConnectionId>, 
/**
 * Les connexions qui quitteraient une lecture seule imposée.
 */
leavesReadOnly: Array<ConnectionId>, 
/**
 * Les dossiers qui imposent ou imposaient la lecture seule — pour que la modale les nomme.
 */
folders: Array<FolderId>, };

/**
 * `recolor_folder`.
 */
export type RecolorFolderRequest = { folder: FolderId, 
/**
 * `None` retire la pastille.
 */
color: FolderColor | null, };

/**
 * `rename_database` : **synchrone** ; ne ferme rien, ne déplace rien, ne touche à aucun secret.
 * Il change `Database::name`, jamais `label`.
 */
export type RenameDatabaseRequest = { connection: ConnectionId, name: string, };

/**
 * `rename_folder` : **synchrone**, ne ferme rien et ne touche à aucun secret.
 */
export type RenameFolderRequest = { folder: FolderId, name: string, };

/**
 * `save_database` : déclarer une connexion **dans un dossier** — le dossier est le cadre d'`A2`.
 *
 * L'identifiant est tiré par le cœur. Le mot de passe voyage en clair et séparé, comme aujourd'hui.
 */
export type SaveDatabaseRequest = { 
/**
 * `None` : à la racine.
 */
folder: FolderId | null, 
/**
 * Le nom technique (`Database::name`). Vide, le cœur y met l'abréviation du moteur.
 */
name: string, engine: Engine, variant: ConnectionSettings, password: string | null, label: string | null, };

/**
 * Ce que `save_database` rend : l'arbre, **et l'identifiant de la connexion créée**, pour que
 * l'écran la sélectionne ou la déplie.
 */
export type SaveDatabaseResult = { tree: FolderTree, connection: ConnectionId, };

/**
 * `set_folder_read_only` — l'effet sur les écrans est celui de #168.
 *
 * Refusé tant qu'une console d'une connexion dont la lecture seule changerait tient une transaction
 * manuelle (#168) : le refus nomme la connexion.
 */
export type SetFolderReadOnlyRequest = { folder: FolderId, readOnly: boolean, };

/**
 * `update_variant` : **ferme toujours** la connexion — l'hôte peut avoir changé.
 */
export type UpdateVariantRequest = { connection: ConnectionId, variant: ConnectionSettings, 
/**
 * `None` laisse le mot de passe en place.
 */
password: string | null, 
/**
 * La valeur définitive du libellé ; vide ou `None` l'efface.
 */
label: string | null, };

/**
 * `save_value_labels` — **le dossier est résolu par le cœur** : celui qui fournit actuellement la
 * table à cette connexion, sinon son dossier racine. Une connexion rangée à la racine est refusée
 * (« rangez la connexion dans un dossier »).
 */
export type ValueLabelsRequest = { connection: ConnectionId, table: string, column: string, 
/**
 * La table vide retire la déclaration de cette colonne.
 */
labels: { [key in string]: string }, };

/**
 * `save_visible_schemas` — ne ferme pas la connexion.
 */
export type VisibleSchemasRequest = { connection: ConnectionId, 
/**
 * La liste vide est un réglage — « aucun ».
 */
schemas: Array<string>, };
