// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * La palette d'accent, **fermée** — les six pastilles du mockup.
 *
 * Les valeurs viennent des propriétés déclarées par le handoff lui-même
 * (`accent.options` de son script de démonstration), et non d'un choix fait ici.
 */
export type Accent = "terracotta" | "framboise" | "brique" | "sauge" | "ardoise" | "violette";

/**
 * L'issue de lecture telle qu'elle traverse l'IPC.
 *
 * Distincte de `LoadOutcome` : le front n'a pas besoin du chemin de quarantaine pour
 * décider quoi afficher, et lui envoyer un chemin absolu du disque de l'utilisateur
 * n'apporterait rien. Il a besoin de savoir **s'il peut écrire**.
 */
export type ConfigLoad = { "kind": "fresh" } | { "kind": "loaded", projects: Array<Project>, 
/**
 * Les préférences (`15a`), **toujours présentes** : leur défaut est une valeur, pas une
 * absence. Une configuration écrite avant `15a` en rend les valeurs du handoff.
 */
preferences: Preferences, } | { "kind": "unreadable", reason: string, 
/**
 * Où l'original a été mis de côté, à montrer pour qu'il soit récupérable.
 */
quarantinedTo: string, } | { "kind": "tooNew", found: number, supported: number, };

/**
 * Les réglages de connexion d'une connexion déclarée. Tout le formulaire de `A2` vit ici, à
 * l'exception du nom, du moteur et de l'environnement, qui appartiennent à la connexion elle-même.
 *
 * **Anciennement `ConnectionSettings`, et le renommage dit le changement de modèle** (`23b`) : ces
 * réglages ne sont plus *une variante parmi plusieurs* d'une même base, mais les réglages d'**une**
 * connexion. Le champ `environment` est monté d'un cran, dans `Database`.
 */
export type ConnectionSettings = { host: string, port: number, defaultDatabase: string, username: string, 
/**
 * Référence vers le mot de passe, jamais le mot de passe. `None` pour un moteur
 * qui n'en demande pas — SQLite sur fichier, par exemple.
 */
password: SecretRef | null, sslMode: SslMode, 
/**
 * Le chemin d'un certificat d'autorité, pour `verify-ca` et `verify-full` (`06f`).
 *
 * **Un chemin de fichier, et c'est le seul mécanisme commun aux trois pilotes.** Ni
 * `mysql_async` ni le pilote MongoDB n'acceptent un `ClientConfig` arbitraire : leur surface est
 * un chemin de CA et des drapeaux. Le trousseau du système n'est donc pas atteignable partout,
 * ce qui a décidé du choix de `rustls` — voir `06f`.
 *
 * `None` signifie « les racines publiques », qui suffisent à un serveur dont le certificat vient
 * d'une autorité connue. Une autorité interne d'entreprise se déclare ici.
 *
 * **`serde(default)` plutôt qu'une migration** : une configuration écrite avant `06f` n'a pas ce
 * champ, et `None` est exactement l'état correct. Même arbitrage qu'en `12f` et `15a`.
 */
caCertificate: string | null, 
/**
 * La base contre laquelle **s'authentifier**, quand elle diffère de celle qu'on ouvre.
 *
 * **MongoDB seul en a besoin, et c'est une propriété du serveur, pas du produit.** Un
 * utilisateur MongoDB appartient à une base, et le pilote s'authentifie contre celle-là. `18b`
 * avait tranché « la base déclarée, jamais `admin` » — supposer `admin` ferait échouer tous ceux
 * qui sont déclarés dans la leur. La décision tient ; ce qui manquait, c'est le cas inverse :
 * l'utilisateur racine que l'image Docker officielle crée (`MONGO_INITDB_ROOT_USERNAME`) vit
 * dans `admin` et n'a **aucun** moyen d'être joint, puisque la base qu'on veut ouvrir n'est pas
 * celle où il est déclaré. Constaté le 26 août 2026 sur un conteneur `mongo:8` : « SCRAM
 * failure: Authentication failed », sans rien à corriger dans le formulaire.
 *
 * `None` garde le comportement de `18b` — la base déclarée fait foi. Le champ n'est donc pas
 * un réglage de plus à comprendre : il ne sert qu'à ceux dont l'utilisateur habite ailleurs.
 *
 * **`serde(default)` plutôt qu'un cran de migration** : un champ *ajouté* n'en demande pas, et
 * `None` est exactement l'état d'une configuration écrite avant. Même arbitrage que
 * `ca_certificate` ci-dessus.
 */
authDatabase: string | null, 
/**
 * Réglage **saisi** dans `A2`. L'état effectif d'une base ouverte compose ce
 * réglage, la préférence globale de `A10` et l'environnement courant : c'est une
 * règle, pas une donnée, et elle appartient à l'édition inline.
 */
readOnly: boolean, reconnectOnStartup: boolean, tunnel: Tunnel | null, };

/**
 * Une console SQL persistée, rattachée à une connexion.
 *
 * Son nom est unique **dans sa connexion**, non dans le projet : deux connexions peuvent chacune
 * porter une console « Exploration », et c'est le cas courant d'une même base déclarée en dev et en
 * prod.
 */
export type Console = { name: string, 
/**
 * Le texte de la console, persisté à chaque frappe utile.
 *
 * Une console vide est **normale** — c'est l'état d'une console qu'on vient de créer — là où une
 * requête enregistrée vide n'aurait rien voulu dire.
 */
sql: string, };

/**
 * Ce que l'écran envoie pour créer, écrire, renommer ou retirer une console.
 *
 * **Elle porte l'identité complète de la connexion** — projet, base, environnement — là où
 * `SavedQueryRequest` de `12f` ne portait que le projet. C'est la conséquence directe du
 * déplacement des consoles sous la connexion : sans l'environnement, `analytics` en dev et
 * `analytics` en prod seraient confondues.
 */
export type ConsoleRequest = { project: string, database: string, environment: EnvironmentId, name: string, 
/**
 * Le texte, pour l'écriture. Ignoré par la création, le renommage et le retrait.
 */
sql: string | null, 
/**
 * Le nouveau nom, pour le renommage.
 */
renameTo: string | null, };

/**
 * Ce que `23e` envoie pour déclarer un environnement de plus.
 */
export type CreateEnvironmentRequest = { project: string, label: string, color: EnvironmentColor, production: boolean, };

/**
 * Ce que `A2` envoie pour créer un projet.
 */
export type CreateProjectRequest = { name: string, 
/**
 * Les environnements que le projet déclare (`24a`).
 *
 * **C'était l'environnement actif, seul.** La création se faisait depuis `A2`, qui ne connaissait
 * que celui de la connexion en cours de déclaration ; le projet recevait le trio de `23a`, figé.
 * Depuis `24a`, la création est un écran à part et les libellés y sont modifiables — parce que
 * `23a` fige l'identifiant au libellé donné **à la création**, et que c'est donc le seul moment où
 * renommer est sans dette.
 *
 * Vide, le cœur reprend le trio par défaut : c'est ce qui garde `08f` vrai pour un appelant qui
 * n'a rien à en dire.
 */
environments: Array<EnvironmentDeclaration>, };

/**
 * Une connexion déclarée : une base, dans **un** environnement (`23b`).
 *
 * # Ce que ce type était, et pourquoi il a changé
 *
 * Il portait `variants: Vec<ConnectionSettings>` — la même base logique déclinée en dev, staging et
 * prod, sous un seul nœud de l'arbre. Décidé le 19 août 2026 : une connexion appartient à un
 * environnement et un seul. `analytics` en dev et `analytics` en prod sont deux connexions, ce qui
 * rend leur nom non unique dans un projet — il l'est dans le couple `(environnement, nom)`.
 *
 * Le nom reste celui de la base distante : il n'y a pas d'étiquette libre. Deux connexions homonymes
 * se distinguent par leur environnement, qui est affiché.
 */
export type Database = { name: string, engine: Engine, environment: EnvironmentId, connection: ConnectionSettings, 
/**
 * Les consoles SQL de cette connexion, telles que l'arbre les montre sous elle.
 *
 * **Sous la connexion, et non sous le projet** — c'est le changement du 20 août 2026, et il
 * renverse l'arbitrage de `12f`. Celui-ci rattachait les requêtes au projet, en faisant valoir
 * qu'un SQL écrit pour `analytics` en prod vaut le plus souvent pour la même base en dev. Mais
 * une console n'est pas un texte réutilisable : c'est un **espace de travail ouvert sur une
 * connexion**, avec son dialecte et son autocomplétion, et le dialecte vient du moteur de cette
 * connexion-là. Une console flottant au-dessus du projet n'aurait pas su lequel employer.
 *
 * Le prix est assumé : le même SQL sur deux environnements demande deux consoles. En échange,
 * chacune sait sur quoi elle s'exécute — ce que « Mes requêtes » ne savait jamais.
 *
 * **`default` plutôt qu'une migration de version**, comme en `12f` et `15a` : une configuration
 * écrite avant ce jour n'a pas ce champ, et le vecteur vide est l'état correct.
 */
consoles: Array<Console>, };

/**
 * Ce que `08j` envoie pour retirer une déclaration de connexion.
 */
export type DeleteDatabaseRequest = { project: string, database: string, 
/**
 * **L'environnement fait partie de l'identité d'une connexion** (`23b`) : sans lui, retirer
 * « analytics » d'un projet qui la déclare en dev et en prod supprimerait la première venue.
 */
environment: EnvironmentId, };

/**
 * Ce que `23f` envoie pour retirer un environnement.
 */
export type DeleteEnvironmentRequest = { project: string, environment: EnvironmentId, };

/**
 * Ce qu'une suppression d'environnement rend à l'écran (`23f`).
 */
export type DeleteEnvironmentResult = { projects: Array<Project>, 
/**
 * Les connexions supprimées, nommées — ce que l'écran redit après coup.
 */
deletedConnections: Array<string>, 
/**
 * Les mots de passe restés dans le trousseau. **Dits, jamais tus.**
 */
leftoverSecrets: Array<string>, };

/**
 * Ce que `08j` envoie pour retirer un projet entier.
 */
export type DeleteProjectRequest = { project: string, };

/**
 * Ce qu'une suppression rend à l'écran (`08j`).
 */
export type DeleteResult = { projects: Array<Project>, 
/**
 * Les mots de passe que le magasin n'a pas su effacer : ils restent dans le Trousseau, et
 * l'utilisateur a le droit de le savoir.
 */
leftoverSecrets: Array<string>, };

/**
 * Les sept moteurs du handoff, et rien d'autre : un moteur inconnu ne compile pas.
 */
export type Engine = "postgresql" | "mysql" | "sqlite" | "mongodb" | "redis" | "snowflake" | "bigquery";

/**
 * La couleur d'un environnement : la pastille du sélecteur, et rien de plus.
 *
 * **Cinq jetons existants, pas un sélecteur de teinte.** Un client de bases n'est pas un éditeur de
 * thème, et une couleur libre finirait par produire des pastilles indistinguables — ce qui coûterait
 * précisément l'information qu'elles portent.
 */
export type EnvironmentColor = "green" | "amber" | "red" | "slate" | "violet";

/**
 * Un environnement **déclaré par un projet** (`23a`).
 */
export type EnvironmentDeclaration = { id: EnvironmentId, label: string, color: EnvironmentColor, 
/**
 * Ce qui déclenche les garde-fous d'écriture (`11d`) et l'encart rouge.
 *
 * **Un drapeau, jamais le libellé.** Un environnement nommé « live » et marqué production doit
 * être protégé ; un environnement nommé « prod » que l'utilisateur n'a pas marqué ne l'est pas.
 * Accrocher une garantie à une chaîne de caractères la rendrait fausse au premier renommage.
 */
production: boolean, };

/**
 * L'identifiant **stable** d'un environnement, dans la portée d'un projet (`23a`).
 *
 * # Pourquoi un identifiant distinct du libellé
 *
 * La référence d'un mot de passe dans le trousseau vaut `dorabase/<projet>/<base>/<environnement>`
 * (`08e`), et c'est cet identifiant qui y figure. S'il suivait le libellé, renommer « prod » en
 * « production » rendrait introuvables **tous les mots de passe du projet** — sans erreur, sans
 * message : des connexions qui redemanderaient leur mot de passe sans raison visible.
 *
 * Il est donc dérivé du libellé **une fois**, à la création, puis figé. C'est exactement le rôle que
 * tenait `EnvironmentId::slug()` quand les environnements étaient une énumération de trois valeurs.
 *
 * # Pourquoi un type nommé et non un `String`
 *
 * Une signature `fn variant(&self, environment: &str)` accepterait un nom de base par erreur. Le type
 * coûte une ligne et rend la confusion impossible — même raison que `SecretRef`.
 */
export type EnvironmentId = string;

/**
 * Les quatre garde-fous d'écriture (`15d`).
 *
 * **Tous à `true` par défaut, y compris pour une installation existante.** `serde(default)` rend
 * `Default::default()`, et un défaut à `false` transformerait une mise à jour de DoraBase en levée
 * silencieuse des garde-fous — exactement ce que `11d` refusait en les livrant non réglables.
 */
export type Guards = { 
/**
 * Le mode de `A6` : toute édition passe par un diff à valider.
 */
pendingBeforeWrite: boolean, 
/**
 * Les bases déclarées `prod` s'ouvrent en lecture seule.
 */
prodReadOnly: boolean, 
/**
 * `DELETE`/`UPDATE` sans `WHERE` sont **refusés**, et non simplement confirmés.
 */
refuseUnrestrictedWrites: boolean, 
/**
 * Le patch inverse est conservé 24 h.
 */
keepInversePatch: boolean, };

/**
 * Les préférences de l'application (`15a`).
 *
 * **Pas des propriétés de projet.** `05b` persiste `{ version, projects }` ; celles-ci s'ajoutent à
 * côté — un thème n'appartient pas à une base. Le champ porte `serde(default)`, comme les requêtes
 * enregistrées de `12f` : une configuration écrite avant `15a` se lit sans préférences, ce qui donne
 * les valeurs par défaut. Pas de migration.
 */
export type Preferences = { theme: Theme, 
/**
 * L'accent, pris dans la palette **fermée** du handoff.
 *
 * Un sélecteur de couleur libre permettrait un accent illisible sur le fond du produit ; le
 * mockup montre six pastilles, et la palette vit dans `tokens.json`.
 */
accent: Accent, 
/**
 * La hauteur d'une ligne de grille, en pixels. `10a` annonçait « `15` la fera varier de 20 à 36 ».
 */
rowHeight: number, 
/**
 * Le corps de la police du code, en dixièmes de point — `125` pour 12,5 pt.
 *
 * **En dixièmes et non en flottant** : un `f32` dans un fichier de configuration écrit
 * `12.5` parfois, `12.499999` ailleurs selon le sérialiseur, et la valeur relue ne serait plus
 * celle qu'on a choisie. Un entier n'a pas ce défaut.
 */
codeFontTenths: number, 
/**
 * Les quatre garde-fous d'écriture (`15d`), **actifs par défaut**.
 */
guards: Guards, };

/**
 * Un projet : ce que la sidebar liste. Pas des connexions — le handoff insiste.
 */
export type Project = { name: string, 
/**
 * Les environnements que **ce projet** déclare (`23a`).
 *
 * Non vide, et sans identifiant en double : les deux invariants sont vérifiés par `valider`.
 * Un projet neuf reçoit `EnvironmentDeclaration::trio_par_defaut`.
 *
 * **Le projet ne porte plus d'environnement actif** (`25c`) : depuis que l'arbre fait de chaque
 * environnement un nœud dépliable (`25a`), aucun écran ne lit plus de choix persisté. Ce qui en
 * tient lieu aujourd'hui — l'ensemble des nœuds dépliés — vit en mémoire.
 */
environments: Array<EnvironmentDeclaration>, databases: Array<Database>, 
/**
 * Les requêtes enregistrées de `12f`, **en transit** : elles deviennent des consoles.
 *
 * Ce champ n'est plus alimenté depuis le 20 août 2026 ; il n'existe que pour ne rien perdre des
 * configurations déjà écrites. `migrer_requetes_en_consoles` le vide au chargement en versant
 * chaque requête dans la première connexion déclarée du projet.
 *
 * **Pourquoi ne pas simplement retirer le champ** : `serde` ignore silencieusement ce qu'il ne
 * connaît pas. Supprimer `queries` du modèle ferait donc disparaître les requêtes de
 * l'utilisateur à la première réécriture du fichier, sans un mot. Un champ conservé et vidé
 * après transfert est ce qui rend la reprise observable.
 *
 * **`skip_serializing_if`** : une fois la migration faite, le champ cesse d'être écrit, et le
 * fichier ne porte plus la trace d'un concept qui n'existe plus. Tant qu'un projet n'a aucune
 * connexion où les verser, en revanche, elles restent dans le fichier et attendent la première.
 */
queries?: Array<SavedQuery>, };

/**
 * Ce qui **diffère** entre les deux sortes de proxy.
 *
 * **Une énumération et non des champs optionnels.** Un `Tunnel` plat portant les champs
 * des deux autoriserait `kind: "cloud-sql"` avec un bastion renseigné et aucune instance.
 * `05a` pose que les invariants sont portés par le typage plutôt qu'en commentaire ; c'en
 * est un. Le coût — un `match` là où il y avait un accès de champ — est le bénéfice :
 * l'ajout d'une troisième sorte fera échouer la compilation aux endroits à traiter.
 *
 * Vérifié : un `match` omettant `CloudSql` échoue en `E0004` (relevé le 19 août 2026).
 */
export type Proxy = { "kind": "ssh" } & ProxySsh | { "kind": "cloud-sql" } & ProxyCloudSql;

/**
 * Le Cloud SQL Auth Proxy de Google. Ouvert par `06g`.
 */
export type ProxyCloudSql = { 
/**
 * `projet:région:instance`, la forme exigée par le proxy. **Non validée ici** :
 * `06g` refuse à l'ouverture, avec le message du proxy lui-même.
 *
 * **Un seul champ, et c'est délibéré** (`06j`, 24 août 2026). Un `credentials_file_path`
 * a existé ici jusqu'à la v3 du fichier de configuration. Il a été retiré parce que
 * l'authentification passe désormais par les identifiants par défaut de l'application
 * (`06i`) : un chemin de compte de service reste possible par la variable
 * `GOOGLE_APPLICATION_CREDENTIALS`, que le proxy lit tout seul, et qui ne coûte ni un
 * champ dans `A2`, ni une valeur à persister. Le cran de migration v3 → v4 retire la
 * clé des fichiers existants.
 *
 * **Et toujours un seul** (`06k`, 24 août 2026). L'authentification IAM de base de
 * données a d'abord été un booléen ici, puis une bascule dans `A2` ; les deux sont
 * partis le jour même, sur décision : le mode est **toujours** actif. Un booléen dont
 * la seule valeur possible est celle que le code applique de toute façon ne décrit rien
 * — il donne seulement l'occasion de diverger.
 */
instanceConnectionName: string, };

/**
 * Un bastion SSH. Le **chemin** de la clé privée est de la configuration, pas un
 * secret.
 */
export type ProxySsh = { bastionHost: string, bastionPort: number, username: string, privateKeyPath: string, };

/**
 * Ce que `23e` envoie pour changer la couleur et le drapeau de production.
 */
export type RecolorEnvironmentRequest = { project: string, environment: EnvironmentId, color: EnvironmentColor, production: boolean, };

/**
 * Ce que `26` envoie pour renommer une connexion.
 *
 * **L'environnement est là parce qu'il fait partie de l'identité** (`23b`) : sans lui, renommer
 * « analytics » dans un projet qui la déclare en dev et en prod viserait la première venue.
 */
export type RenameDatabaseRequest = { project: string, database: string, environment: EnvironmentId, name: string, };

/**
 * Ce que `23e` envoie pour changer le libellé d'un environnement.
 */
export type RenameEnvironmentRequest = { project: string, 
/**
 * **L'identifiant, non l'ancien libellé** : c'est lui qui désigne, et lui qui ne change jamais
 * (`23a`). Désigner par le libellé rendrait le geste impossible sur deux environnements dont les
 * libellés ont divergé de leurs identifiants.
 */
environment: EnvironmentId, label: string, };

/**
 * Ce que `08i` envoie pour renommer un projet.
 */
export type RenameProjectRequest = { project: string, name: string, };

/**
 * Ce qu'un renommage réussi rend à l'écran — celui d'un projet (`08i`) comme celui d'une connexion
 * (`26`).
 *
 * **Un seul type pour les deux**, et c'est pourquoi il ne s'appelle plus `RenameProjectResult` : les
 * deux commandes déplacent des secrets et ont exactement les mêmes trois choses à rapporter. Deux
 * types identiques auraient divergé au premier champ ajouté à l'un.
 *
 * **Pas seulement les projets.** Deux faits méritent d'être dits plutôt que tus : des mots de passe
 * déclarés mais introuvables — les bases les redemanderont — et des originaux que le magasin n'a
 * pas su effacer. Les taire laisserait l'utilisateur découvrir l'un ou l'autre bien plus tard.
 */
export type RenameResult = { projects: Array<Project>, missingSecrets: Array<string>, leftoverSecrets: Array<string>, };

/**
 * Ce que `23e` envoie après un glissement.
 */
export type ReorderEnvironmentsRequest = { project: string, 
/**
 * L'ordre complet, dans l'ordre voulu. Une permutation partielle est refusée (`23c`).
 */
order: Array<EnvironmentId>, };

/**
 * Ce que `A2` envoie en cliquant « Enregistrer & ouvrir ».
 *
 * Le mot de passe est **en clair et séparé**, comme dans `ConnectionRequest` de `08d` : aucune
 * `SecretRef` n'existe avant que le secret soit rangé, et c'est justement le travail de cette
 * commande. La variante reçue porte donc `password: null`, que `enregistrer` remplace.
 */
export type SaveDatabaseRequest = { project: string, database: string, engine: Engine, 
/**
 * L'environnement choisi dans `A2`, parmi ceux du projet (`23d`).
 */
environment: EnvironmentId, variant: ConnectionSettings, password: string | null, };

/**
 * Une requête enregistrée (`12f`), **en transit** — voir `Project::queries`.
 */
export type SavedQuery = { name: string, sql: string, };

/**
 * Le mécanisme réellement employé, tel que le front l'apprend.
 *
 * Le badge vert « Trousseau » de `A2` serait un mensonge en développement : l'écran doit
 * pouvoir dire la vérité, donc il a besoin de cette information.
 */
export type SecretMechanism = "keychain" | "encryptedFile";

/**
 * Référence vers un secret rangé par `05c` — **jamais sa valeur**.
 *
 * Type distinct plutôt qu'un alias de `String` : une valeur de secret ne peut pas y
 * être affectée par erreur, puisqu'aucune conversion implicite n'existe. Rien à
 * divulguer ici de toute façon, une référence n'est pas un secret.
 */
export type SecretRef = string & { readonly __secretRef: unique symbol };

export type SslMode = "disable" | "allow" | "prefer" | "require" | "verify-ca" | "verify-full";

/**
 * Les trois thèmes du mockup.
 */
export type Theme = "cahier" | "nuit" | "systeme";

/**
 * Le panneau « Proxy / tunnel » de `A2`, tel qu'il est configuré.
 */
export type Tunnel = { 
/**
 * `None` signifie « auto » — le port local est choisi à l'ouverture par `06`.
 *
 * **Hors de `Proxy`, et c'est le point** : il est vrai des deux sortes. Le dupliquer
 * dans chaque variante obligerait chaque lecteur à faire un `match` pour lire une
 * donnée qui ne varie pas.
 */
localPort: number | null, proxy: Proxy, };

/**
 * Ce que `A2` envoie en mode édition (`08g`).
 */
export type UpdateVariantRequest = { project: string, database: string, 
/**
 * L'environnement **désigne** la variante ; il ne se modifie pas. Voir `08g`.
 */
environment: EnvironmentId, variant: ConnectionSettings, 
/**
 * `None` laisse le mot de passe en place — un champ vide veut dire « inchangé ».
 */
password: string | null, };
