// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * La palette d'accent, **fermée** — les six pastilles du mockup.
 *
 * Les valeurs viennent des propriétés déclarées par le handoff lui-même
 * (`accent.options` de son script de démonstration), et non d'un choix fait ici.
 */
export type Accent = "terracotta" | "framboise" | "brique" | "sauge" | "ardoise" | "violette";

/**
 * L'identifiant stable d'une connexion (#164).
 *
 * **Figé à la création, jamais dérivé du nom ni du dossier** : c'est ce qui fait qu'un renommage ou
 * un déplacement ne le périme pas. Il n'a aucun sens lisible, et c'est voulu — un identifiant
 * lisible dérivé du libellé, comme `InstanceId`, ferait que deux postes créant chacun une « psql »
 * produisent le même, et l'import les prendrait pour la même connexion.
 *
 * `#[ts(type = "string")]`, comme `EnvironmentId` : `ts-rs` projetterait sinon la structure et non
 * la chaîne qu'elle transporte.
 */
export type ConnectionId = string;

/**
 * Les réglages de connexion d'une connexion déclarée. Tout le formulaire de `A2` vit ici, à
 * l'exception du nom, du moteur et de l'environnement, qui appartiennent à la connexion elle-même.
 *
 * **Anciennement `ConnectionSettings`, et le renommage dit le changement de modèle** (`23b`) : ces
 * réglages ne sont plus *une variante parmi plusieurs* d'une même base, mais les réglages d'**une**
 * connexion. Le champ `environment` est monté d'un cran, dans `Database`.
 */
export type ConnectionSettings = { host: string, port: number, defaultDatabase: string, username: string, 
/**
 * Référence vers le mot de passe, jamais le mot de passe. `None` pour un moteur
 * qui n'en demande pas — SQLite sur fichier, par exemple.
 */
password: SecretRef | null, sslMode: SslMode, 
/**
 * Le chemin d'un certificat d'autorité, pour `verify-ca` et `verify-full` (`06f`).
 *
 * **Un chemin de fichier, et c'est le seul mécanisme commun aux trois pilotes.** Ni
 * `mysql_async` ni le pilote MongoDB n'acceptent un `ClientConfig` arbitraire : leur surface est
 * un chemin de CA et des drapeaux. Le trousseau du système n'est donc pas atteignable partout,
 * ce qui a décidé du choix de `rustls` — voir `06f`.
 *
 * `None` signifie « les racines publiques », qui suffisent à un serveur dont le certificat vient
 * d'une autorité connue. Une autorité interne d'entreprise se déclare ici.
 *
 * **`serde(default)` plutôt qu'une migration** : une configuration écrite avant `06f` n'a pas ce
 * champ, et `None` est exactement l'état correct. Même arbitrage qu'en `12f` et `15a`.
 */
caCertificate: string | null, 
/**
 * La base contre laquelle **s'authentifier**, quand elle diffère de celle qu'on ouvre.
 *
 * **MongoDB seul en a besoin, et c'est une propriété du serveur, pas du produit.** Un
 * utilisateur MongoDB appartient à une base, et le pilote s'authentifie contre celle-là. `18b`
 * avait tranché « la base déclarée, jamais `admin` » — supposer `admin` ferait échouer tous ceux
 * qui sont déclarés dans la leur. La décision tient ; ce qui manquait, c'est le cas inverse :
 * l'utilisateur racine que l'image Docker officielle crée (`MONGO_INITDB_ROOT_USERNAME`) vit
 * dans `admin` et n'a **aucun** moyen d'être joint, puisque la base qu'on veut ouvrir n'est pas
 * celle où il est déclaré. Constaté le 26 août 2026 sur un conteneur `mongo:8` : « SCRAM
 * failure: Authentication failed », sans rien à corriger dans le formulaire.
 *
 * `None` garde le comportement de `18b` — la base déclarée fait foi. Le champ n'est donc pas
 * un réglage de plus à comprendre : il ne sert qu'à ceux dont l'utilisateur habite ailleurs.
 *
 * **`serde(default)` plutôt qu'un cran de migration** : un champ *ajouté* n'en demande pas, et
 * `None` est exactement l'état d'une configuration écrite avant. Même arbitrage que
 * `ca_certificate` ci-dessus.
 */
authDatabase: string | null, 
/**
 * Réglage **saisi** dans `A2`. L'état effectif d'une base ouverte compose ce
 * réglage, la préférence globale de `A10` et l'environnement courant : c'est une
 * règle, pas une donnée, et elle appartient à l'édition inline.
 */
readOnly: boolean, reconnectOnStartup: boolean, tunnel: Tunnel | null, };

/**
 * Une console SQL persistée, rattachée à une connexion.
 *
 * Son nom est unique **dans sa connexion**, non dans le projet : deux connexions peuvent chacune
 * porter une console « Exploration », et c'est le cas courant d'une même base déclarée en dev et en
 * prod.
 */
export type Console = { name: string, 
/**
 * Le texte de la console, persisté à chaque frappe utile.
 *
 * Une console vide est **normale** — c'est l'état d'une console qu'on vient de créer — là où une
 * requête enregistrée vide n'aurait rien voulu dire.
 */
sql: string, };

/**
 * Une connexion déclarée : une feuille de l'arbre de dossiers (#164, #165).
 *
 * # Ce qui la désigne
 *
 * **Son identifiant, et rien d'autre.** Elle fut désignée par le triplet `projet/base/environnement`,
 * qui était à la fois la clé du registre et la référence du secret : renommer un projet obligeait
 * donc à déplacer des secrets et à fermer des connexions. Depuis #165, `id` est figé à la création,
 * ne dit rien du dossier qui la range, et c'est de lui seul que dérivent la clé du registre et la
 * référence du mot de passe (`cle_de_connexion`, `reference_de_connexion`).
 *
 * **`name` n'est plus une identité**, donc plus unique nulle part : deux « psql » peuvent vivre
 * dans le même dossier. Il reste le nom technique de repli — `A2` ne le fait plus saisir, le cœur y
 * met l'abréviation du moteur ([`Engine::nom_par_defaut`]) —, et `label`, s'il est renseigné, le
 * **remplace** partout où l'arbre, le fil d'Ariane et la barre de titre l'affichent.
 */
export type Database = { 
/**
 * L'identifiant stable de la connexion : clé du registre et référence du secret, figé à la
 * création et indépendant du dossier qui la contient.
 *
 * **Obligatoire, dans le fichier comme dans sa projection TypeScript** (#165) : un fichier v6,
 * qui n'en portait pas, ne se relit plus par ce type mais par `migration::v6`, qui le dérive.
 */
id: ConnectionId, name: string, 
/**
 * Le nom d'affichage, quand il diffère de `name`. `None` ou vide : `name` fait foi.
 *
 * **`#[serde(default)]` : aucune migration.** Une configuration écrite avant ce champ n'en a
 * simplement pas — `27a` en tient la règle.
 */
label?: string | null, engine: Engine, connection: ConnectionSettings, 
/**
 * Les consoles SQL de cette connexion, telles que l'arbre les montre sous elle.
 *
 * **Sous la connexion, et non sous le projet** — c'est le changement du 20 août 2026, et il
 * renverse l'arbitrage de `12f`. Celui-ci rattachait les requêtes au projet, en faisant valoir
 * qu'un SQL écrit pour `analytics` en prod vaut le plus souvent pour la même base en dev. Mais
 * une console n'est pas un texte réutilisable : c'est un **espace de travail ouvert sur une
 * connexion**, avec son dialecte et son autocomplétion, et le dialecte vient du moteur de cette
 * connexion-là. Une console flottant au-dessus du projet n'aurait pas su lequel employer.
 *
 * Le prix est assumé : le même SQL sur deux environnements demande deux consoles. En échange,
 * chacune sait sur quoi elle s'exécute — ce que « Mes requêtes » ne savait jamais.
 *
 * **`default` plutôt qu'une migration de version**, comme en `12f` et `15a` : une configuration
 * écrite avant ce jour n'a pas ce champ, et le vecteur vide est l'état correct.
 */
consoles: Array<Console>, 
/**
 * Les schémas que l'arbre montre sous cette connexion, ou `None` : tous les non-système
 * (`API-33`).
 *
 * **`None` n'est pas la liste vide.** `None` veut dire « jamais réglé » — l'arbre affiche
 * alors ce qu'il a toujours affiché, les schémas non-système, donc aucune configuration
 * existante ne voit son arbre changer. La liste vide, elle, est un réglage : quelqu'un a tout
 * décoché. C'est la même distinction que « jamais tentée » et « hors ligne » pour l'état d'une
 * connexion, et que `pas encore cherché` / `à jour` pour les mises à jour : quatre états, pas
 * deux.
 *
 * **Une préférence, pas une capacité** : elle ne change rien à ce que la connexion peut lire —
 * une console interroge ce qu'elle veut. Elle vit donc à côté de la connexion et non dans
 * `ConnectionSettings`, dont chaque champ décrit *comment joindre le serveur*.
 *
 * **`#[serde(default)]` : aucun cran de migration**, la règle des champs ajoutés de `27a`. Et
 * `skip_serializing_if` pour qu'une connexion jamais réglée n'écrive pas un `null` dans le
 * fichier.
 */
visibleSchemas?: Array<string> | null, };

/**
 * La lecture seule effective d'une connexion (#164, lue par #168).
 *
 * Projetée en `EffectiveReadOnly` : c'est la forme que la fixture partagée
 * `tests/fixtures/lecture-seule.json` écrit, et que le miroir TypeScript de #168 doit rendre.
 */
export type EffectiveReadOnly = { "kind": "imposed", folders: Array<FolderId>, } | { "kind": "local", readOnly: boolean, };

/**
 * Les sept moteurs du handoff, et rien d'autre : un moteur inconnu ne compile pas.
 */
export type Engine = "postgresql" | "mysql" | "sqlite" | "mongodb" | "redis" | "snowflake" | "bigquery";

/**
 * Un dossier de l'arbre (#164).
 *
 * # Les libellés de valeurs vivent ici
 *
 * La migration les pose sur le dossier racine issu du projet, ce qui reproduit la sémantique
 * d'`API-75` : partagés entre dev, staging et prod. La résolution se fait **table par table**, et le
 * dossier le plus proche qui déclare la table l'emporte **entièrement** — voir
 * [`FolderTree::libelles_de`].
 */
export type Folder = { id: FolderId, 
/**
 * Renommable, et **jamais une identité**.
 */
name: string, 
/**
 * `None` : aucune pastille — la teinte par défaut de l'arbre.
 */
color?: FolderColor | null, 
/**
 * La lecture seule, qui s'impose à **tous** les descendants (#108) : un sous-dossier ou une
 * connexion ne peut pas la lever pour lui-même.
 *
 * **Toujours écrit**, même faux : c'est un garde-fou, et un fichier qui le tairait ne se
 * relirait pas d'un coup d'œil.
 */
readOnly: boolean, 
/**
 * Les sous-dossiers, **dans l'ordre déclaré** — l'ordre dev/staging/prod voulu par l'utilisateur
 * survit à la migration, et aucun tri alphabétique ne le défait.
 */
folders?: Array<Folder>, 
/**
 * Les connexions rangées directement ici, dans l'ordre déclaré.
 */
connections?: Array<Database>, valueLabels?: { [key in string]: { [key in string]: { [key in string]: string } } }, 
/**
 * Les requêtes de `12f` encore en transit : un projet v6 sans connexion n'avait nulle part où
 * les verser. Même règle que `Project::queries` — elles attendent la première connexion du
 * sous-arbre.
 */
queries?: Array<SavedQuery>, };

/**
 * La pastille d'un dossier : les cinq jetons existants, et rien de plus.
 *
 * **Anciennement `EnvironmentColor`, aux mêmes valeurs `kebab-case`** : le JSON d'une couleur
 * d'environnement v6 se relit donc tel quel en couleur de dossier, ce dont la migration dépend.
 * La raison des cinq jetons n'a pas changé — une couleur libre finirait par produire des pastilles
 * indistinguables.
 */
export type FolderColor = "green" | "amber" | "red" | "slate" | "violet";

/**
 * L'identifiant stable d'un dossier (#164). Mêmes règles que [`ConnectionId`].
 *
 * **Un dossier a une identité, bien qu'il s'apparie par son nom à l'import** (#169) : le déplacer,
 * le renommer ou le recolorier doit le désigner sans ambiguïté, et deux dossiers homonymes peuvent
 * vivre sous deux parents différents.
 */
export type FolderId = string;

/**
 * La racine de l'arbre : **pas un dossier**, donc ni nom, ni couleur, ni lecture seule.
 *
 * **Imbriqué plutôt qu'à plat** (une liste de dossiers portant un `parent`) : un cycle ou un parent
 * mort deviennent inexprimables, l'export d'un sous-arbre est un clonage, et le fichier se lit à la
 * main. Le prix — une recherche par identifiant est un parcours — ne pèse rien à cette taille.
 */
export type FolderTree = { folders: Array<Folder>, 
/**
 * Les connexions rangées à la racine, hors de tout dossier.
 */
connections: Array<Database>, };

/**
 * Les trois garde-fous d'écriture (`15d`).
 *
 * **Ils étaient quatre** : `prod_read_only` — « les bases déclarées `prod` s'ouvrent en lecture
 * seule » — est parti avec #168. Il n'avait aucun lecteur, et la lecture seule d'un dossier, qui
 * s'impose à tous ses descendants, ne laisse plus rien à régler : un réglage qui ne change rien
 * n'est pas un choix offert. Un fichier qui le porte encore se relit sans lui — `serde` ignore le
 * champ, et la prochaine écriture le retire ; il n'y avait rien à reprendre, donc aucun cran.
 *
 * **Tous à `true` par défaut, y compris pour une installation existante.** `serde(default)` rend
 * `Default::default()`, et un défaut à `false` transformerait une mise à jour de DoraBase en levée
 * silencieuse des garde-fous — exactement ce que `11d` refusait en les livrant non réglables.
 */
export type Guards = { 
/**
 * Le mode de `A6` : toute édition passe par un diff à valider.
 */
pendingBeforeWrite: boolean, 
/**
 * `DELETE`/`UPDATE` sans `WHERE` sont **refusés**, et non simplement confirmés.
 */
refuseUnrestrictedWrites: boolean, 
/**
 * Le patch inverse est conservé 24 h.
 */
keepInversePatch: boolean, };

/**
 * L'identifiant **stable** d'une instance managée (`API-32`).
 *
 * # Pourquoi un identifiant distinct du libellé
 *
 * C'est exactement la raison d'`EnvironmentId`, appliquée à une instance : il est à la fois la clé
 * du registre de connexions (`instance/<id>`) et la référence du mot de passe dans le Trousseau. Un
 * identifiant qui suivrait le libellé rendrait le secret introuvable au premier renommage — sans
 * erreur, sans message, avec une instance qui redemanderait son mot de passe sans raison visible.
 *
 * Il est donc dérivé du libellé **une fois**, à la déclaration, puis figé. Renommer une instance
 * change son libellé seul, et installe la divergence assumée que le projet a déjà acceptée pour un
 * environnement et pour une connexion.
 */
export type InstanceId = string;

/**
 * Un kubeconfig déclaré une fois pour toutes, que les connexions désignent (`API-70`).
 *
 * **Pourquoi ce type existe** : un cluster porte souvent des dizaines de bases, donc le même
 * fichier était ressaisi connexion par connexion. Le déclarer une fois retire la ressaisie, et la
 * **référence** retire la mise à jour en masse — déplacer le fichier se fait ici, et les connexions
 * suivent.
 */
export type KubeconfigDeclaration = { 
/**
 * Figé à la déclaration. Voir [`KubeconfigId`].
 */
id: KubeconfigId, 
/**
 * Ce que l'écran affiche. Peut diverger de l'identifiant, et c'est voulu.
 */
label: string, 
/**
 * Le chemin du fichier, tel que l'utilisateur l'a donné.
 *
 * **Pas développé ici** : le `~/` de tête l'est par `programme::chemin_utilisateur`, au moment
 * de lancer `kubectl`, et là seulement. Développer en écrivant persisterait un chemin absolu
 * que personne n'a saisi, donc une déclaration qui cesse d'être vraie sous un autre compte.
 */
path: string, };

/**
 * L'identifiant **stable** d'un kubeconfig déclaré (`API-70`).
 *
 * C'est la raison d'`EnvironmentId` et d'`InstanceId`, pour la troisième fois : une connexion
 * Kubernetes garde une **référence** vers la déclaration, pas son chemin. Si l'identifiant suivait
 * le libellé, renommer « prod » en « production » détacherait toutes les connexions qui s'y
 * rattachent — sans erreur, sans message, et la suivante ouvrirait le kubeconfig **par défaut de
 * `kubectl`**, c'est-à-dire un autre cluster, avec succès. C'est le mode de défaillance que ce
 * dossier redoute le plus : se tromper d'espace de noms se voit, se tromper de cluster réussit.
 *
 * Il est donc dérivé du libellé **une fois**, à la déclaration, puis figé. Renommer une déclaration
 * change son libellé seul ; **déplacer le fichier change son chemin seul**, et c'est précisément ce
 * que la référence achète — toutes les connexions suivent, sans qu'aucune soit rouverte.
 */
export type KubeconfigId = string;

/**
 * Les kubeconfigs déclarés, et celui qui prérègle une connexion neuve (`API-70`).
 *
 * **Un type plutôt que deux champs à la racine du fichier** : l'invariant « le défaut nomme une
 * déclaration qui existe » n'a alors qu'un seul lieu où il peut être faux, et [`Kubeconfigs::valider`]
 * y répond. Deux champs voisins auraient laissé chaque écrivain le tenir de son côté.
 */
export type Kubeconfigs = { declarations?: Array<KubeconfigDeclaration>, 
/**
 * Celui qui préremplit une connexion Kubernetes **neuve**, et rien de plus.
 *
 * **Jamais appliqué à une connexion déjà enregistrée** : changer le défaut repointerait en
 * silence des connexions qui marchent, ce qu'`update_variant` ferme une connexion pour éviter.
 */
default?: KubeconfigId | null, };

/**
 * La langue de l'interface (26 août 2026).
 *
 * **Le même mécanisme que `Theme`** : une variante `Systeme` que l'écran résout lui-même,
 * plutôt qu'un défaut Rust deviné. La détection — `navigator.language` — vit dans la
 * webview, qui la porte déjà sans dépendance Rust ni appel IPC ; le cœur ne connaît que
 * le réglage choisi, jamais la langue résolue.
 */
export type Language = "fr" | "en" | "systeme";

/**
 * Une instance de serveur **managée** (`API-32`).
 *
 * # Ce qu'elle n'est pas
 *
 * Ce n'est pas une connexion de plus. Une `Database` désigne **une base** dans un projet, pour un
 * environnement, et sert à en lire les données ; une instance désigne **le serveur**, joint avec un
 * compte d'administration, et sert à en gérer les bases, les rôles et les privilèges. Les deux
 * pourraient viser le même hôte sans que cela veuille dire quoi que ce soit : l'une est déclarée par
 * un projet, l'autre vit à côté des projets — c'est ce que la seconde zone de la sidebar dit à
 * l'œil.
 *
 * Les fondre aurait demandé qu'une `Database` porte un drapeau « c'est aussi une instance », donc
 * que chaque écran qui liste des connexions sache l'écarter, et que le registre de projets se
 * mette à porter des objets qui n'appartiennent à aucun environnement.
 *
 * # PostgreSQL seul, et le champ `engine` existe quand même
 *
 * La modale rend les trois autres moteurs **désactivés avec leur raison** plutôt que masqués : ils
 * viennent après, et masquer dirait « jamais ». Le champ persiste ce choix pour que le jour où
 * MySQL arrive, aucune migration ne soit nécessaire — et pour que le refus côté Rust porte sur une
 * valeur lue, non sur une supposition.
 */
export type ManagedInstance = { 
/**
 * L'identité figée : clé du registre, référence du secret.
 */
id: InstanceId, 
/**
 * Ce que la ligne de la sidebar affiche. Se renomme ; l'identifiant, non.
 */
label: string, engine: Engine, 
/**
 * Hôte, port, base de service, utilisateur admin, mode SSL, proxy — tout le formulaire.
 *
 * **Le même type que pour une connexion, et c'est ce qui donne le panneau « Proxy / tunnel »
 * gratuitement.** Une instance managée se joint par un bastion aussi souvent qu'une base ; en
 * réécrire un jeu de champs propre aurait fait vivre deux fois les trois visages de proxy, leur
 * validation et leur ouverture — la règle n° 17 par avance.
 */
connection: ConnectionSettings, 
/**
 * Ce qui déclenche le rappel des bandes destructrices.
 *
 * **Un drapeau, jamais le libellé** : la règle d'`EnvironmentDeclaration::production`, pour la
 * raison qui y est écrite. Une instance nommée « live » et marquée production est protégée ;
 * une instance nommée « prod » que personne n'a marquée ne l'est pas.
 */
production: boolean, 
/**
 * « Confirmer chaque écriture » — la première des deux bascules de la modale.
 *
 * **Allumée par défaut, y compris pour une instance écrite avant ce champ.** `bool` retomberait
 * à `false` sous `serde(default)`, ce qui ferait d'une mise à jour de DoraBase une levée
 * silencieuse du garde-fou : c'est exactement ce que `Guards` refuse, et la parade est la même —
 * un défaut explicite plutôt que celui du type.
 */
confirmWrites: boolean, };

/**
 * Les préférences de l'application (`15a`).
 *
 * **Pas des propriétés de projet.** `05b` persiste `{ version, projects }` ; celles-ci s'ajoutent à
 * côté — un thème n'appartient pas à une base. Le champ porte `serde(default)`, comme les requêtes
 * enregistrées de `12f` : une configuration écrite avant `15a` se lit sans préférences, ce qui donne
 * les valeurs par défaut. Pas de migration.
 */
export type Preferences = { theme: Theme, 
/**
 * La langue de l'interface (26 août 2026), défaut `Systeme`.
 */
language: Language, 
/**
 * L'accent, pris dans la palette **fermée** du handoff.
 *
 * Un sélecteur de couleur libre permettrait un accent illisible sur le fond du produit ; le
 * mockup montre six pastilles, et la palette vit dans `tokens.json`.
 */
accent: Accent, 
/**
 * La hauteur d'une ligne de grille, en pixels. `10a` annonçait « `15` la fera varier de 20 à 36 ».
 */
rowHeight: number, 
/**
 * Le corps de la police du code, en dixièmes de point — `125` pour 12,5 pt.
 *
 * **En dixièmes et non en flottant** : un `f32` dans un fichier de configuration écrit
 * `12.5` parfois, `12.499999` ailleurs selon le sérialiseur, et la valeur relue ne serait plus
 * celle qu'on a choisie. Un entier n'a pas ce défaut.
 */
codeFontTenths: number, 
/**
 * Les quatre garde-fous d'écriture (`15d`), **actifs par défaut**.
 */
guards: Guards, };

/**
 * Ce qui **diffère** entre les trois sortes de proxy.
 *
 * **Une énumération et non des champs optionnels.** Un `Tunnel` plat portant les champs
 * des trois autoriserait `kind: "cloud-sql"` avec un bastion renseigné et aucune instance.
 * `05a` pose que les invariants sont portés par le typage plutôt qu'en commentaire ; c'en
 * est un. Le coût — un `match` là où il y avait un accès de champ — est le bénéfice :
 * l'ajout d'une troisième sorte fera échouer la compilation aux endroits à traiter.
 *
 * **Et c'est ce qui s'est passé** (31 août 2026), à une nuance qui vaut d'être relevée. Mesuré par
 * sabotage — variante ajoutée ici, `engine/proxy.rs` remis dans son état d'avant : `Kubernetes` a
 * fait échouer la compilation en `E0004` à **un seul** endroit du dépôt, `ProxyOuvert::ouvrir`.
 * Un seul, parce que c'est le seul `match` sur *ce* type : les trois autres de `proxy.rs` — port
 * local, état, fermeture — portent sur `ProxyOuvert`, qui est une **autre** énumération et qui
 * restait exhaustive tant qu'elle n'avait pas sa propre variante.
 *
 * La garantie n'en est pas affaiblie, elle est en **deux temps**, et il faut le savoir pour ne pas
 * la croire plus courte qu'elle est : cette énumération oblige à traiter l'ouverture, et c'est
 * l'ouverture qui oblige à donner une variante à `ProxyOuvert` — laquelle oblige alors les trois
 * autres. Aucun des quatre n'aurait été retrouvé par relecture.
 *
 * **Aucun cran de migration n'a été nécessaire** : une variante *ajoutée* ne périme aucun fichier
 * existant, dont l'étiquette reste lisible. C'est la règle des champs de `27a`, appliquée à une
 * étiquette — et l'inverse d'un retrait, qui en demande un (`06j`).
 *
 * Vérifié : un `match` omettant `CloudSql` échoue en `E0004` (relevé le 19 août 2026).
 */
export type Proxy = { "kind": "ssh" } & ProxySsh | { "kind": "cloud-sql" } & ProxyCloudSql | { "kind": "kubernetes" } & ProxyKubernetes;

/**
 * Le Cloud SQL Auth Proxy de Google. Ouvert par `06g`.
 */
export type ProxyCloudSql = { 
/**
 * `projet:région:instance`, la forme exigée par le proxy. **Non validée ici** :
 * `06g` refuse à l'ouverture, avec le message du proxy lui-même.
 *
 * **Un seul champ, et c'est délibéré** (`06j`, 24 août 2026). Un `credentials_file_path`
 * a existé ici jusqu'à la v3 du fichier de configuration. Il a été retiré parce que
 * l'authentification passe désormais par les identifiants par défaut de l'application
 * (`06i`) : un chemin de compte de service reste possible par la variable
 * `GOOGLE_APPLICATION_CREDENTIALS`, que le proxy lit tout seul, et qui ne coûte ni un
 * champ dans `A2`, ni une valeur à persister. Le cran de migration v3 → v4 retire la
 * clé des fichiers existants.
 *
 * **Et toujours un seul** (`06k`, 24 août 2026). L'authentification IAM de base de
 * données a d'abord été un booléen ici, puis une bascule dans `A2` ; les deux sont
 * partis le jour même, sur décision : le mode est **toujours** actif. Un booléen dont
 * la seule valeur possible est celle que le code applique de toute façon ne décrit rien
 * — il donne seulement l'occasion de diverger.
 */
instanceConnectionName: string, };

/**
 * Un transfert de port Kubernetes — `kubectl port-forward`, lancé en sous-processus.
 *
 * **Ce que cette sorte a de particulier** (31 août 2026) : une base dans un cluster n'a pas
 * d'adresse joignable depuis le poste. Ce n'est donc pas un hôte qui la désigne, mais une
 * **ressource** dans un **espace de noms**, lus dans un **kubeconfig**.
 *
 * **Le contexte ne se choisit pas : il vient du kubeconfig** (31 août 2026, second passage). Un
 * champ `context` a existé ici une demi-journée, avec un long commentaire sur l'inconfort d'un
 * contexte optionnel. Il est parti à l'usage : un kubeconfig désigne son contexte courant, et
 * l'outil qui l'a écrit — Freelens, `gcloud`, `kind` — en produit un par cluster. Déclarer le
 * contexte revenait donc à recopier une information que le **fichier** porte déjà, et le fichier,
 * lui, se déclare.
 *
 * Ce qui reste de l'arbitrage d'origine : le contexte est **deviné**, toujours, donc il doit être
 * **dit**. L'en-tête du journal du transfert porte celui que `kubectl config current-context` a
 * rendu, et voyage dans tout message d'échec. C'est la seule façon de savoir quel cluster on a
 * joint, et elle compte davantage maintenant qu'aucun champ ne l'affirme.
 */
export type ProxyKubernetes = { 
/**
 * Le kubeconfig à employer, **par référence** à une déclaration de [`Kubeconfigs`] (`API-70`).
 * `None` : celui que `kubectl` choisirait — `$KUBECONFIG`, à défaut `~/.kube/config`.
 *
 * **Ce champ existe parce qu'une app graphique n'hérite pas de `$KUBECONFIG`** (31 août 2026).
 * C'est le même fait qui a imposé l'enrichissement du `PATH`, appliqué à une autre variable :
 * macOS ne donne à une application lancée depuis le Finder aucun des exports du shell. Le
 * défaut `~/.kube/config` survit — `HOME`, lui, est transmis —, mais un
 * `export KUBECONFIG=~/.kube/prod:~/.kube/staging`, qui est la façon courante de tenir
 * plusieurs clusters, ne parvient pas jusqu'à nous. Sans ce champ, les contextes de ces
 * fichiers seraient **invisibles depuis l'app** alors que `kubectl config get-contexts` les
 * liste dans un terminal, et l'échec dirait « context not found » : un message qui accuse une
 * installation correcte.
 *
 * **Un chemin, pas une liste.** `$KUBECONFIG` accepte plusieurs fichiers séparés par `:`, que
 * `kubectl` fusionne ; `--kubeconfig` n'en prend qu'un. Le cas de la fusion n'est donc pas
 * couvert, et c'est assumé : une connexion vise **un** cluster, donc le fichier qui le déclare
 * suffit à la décrire.
 *
 * **Une référence et non le chemin, depuis `API-70`.** Un cluster porte souvent des dizaines de
 * bases : le chemin était ressaisi à chaque connexion, et le déplacer demandait de rouvrir
 * chacune. La référence met le chemin en **un** lieu. Ce qu'elle coûte est que le chemin n'est
 * plus lisible ici : il faut les déclarations pour l'obtenir, d'où le `ContexteDeProxy` que
 * l'ouverture reçoit — et un `#[serde(skip)]` qu'un appelant aurait dû remplir a été écarté
 * pour cela, l'oubli ouvrant **le cluster par défaut de `kubectl`, avec succès**.
 */
kubeconfig?: KubeconfigId | null, 
/**
 * L'espace de noms. `None` : celui que `kubectl` emploierait — celui du contexte s'il en
 * déclare un, `default` sinon.
 *
 * **Un espace de noms absent est bénin, et c'est ce qui le distingue du cluster** : il fait
 * échouer `kubectl` sur « not found », donc bruyamment. C'est aussi pourquoi il n'est pas tracé
 * dans l'en-tête du journal alors que le contexte l'est : se tromper d'espace de noms se voit,
 * se tromper de cluster **réussit**.
 */
namespace?: string | null, 
/**
 * La ressource à joindre, dans la forme que `kubectl port-forward` accepte : `svc/postgres`,
 * `pod/postgres-0`, `statefulset/postgres`, ou un nom nu — que `kubectl` lit comme un pod.
 *
 * **Transmise telle quelle, jamais réécrite.** Deux raisons : la liste des types que `kubectl`
 * accepte est la sienne et grandit sans nous, et le projet ne corrige aucune saisie (voir
 * « Aucune correction automatique dans les champs »). Un `svc/` ajouté d'office viserait un
 * service là où l'utilisateur nommait un pod.
 *
 * **Un pod nommé à la main se périme, et c'est à l'utilisateur de le savoir** : le suffixe
 * aléatoire d'un `Deployment` change à chaque redéploiement. Le placeholder de `A2` propose
 * donc `svc/…`, qui survit — mais refuser un nom de pod interdirait le seul geste possible
 * quand aucun service n'expose la base.
 */
resource: string, };

/**
 * Un bastion SSH. Le **chemin** de la clé privée est de la configuration, pas un
 * secret.
 */
export type ProxySsh = { bastionHost: string, bastionPort: number, username: string, privateKeyPath: string, };

/**
 * Une requête enregistrée (`12f`), **en transit** — voir `Folder::queries`.
 */
export type SavedQuery = { name: string, sql: string, };

/**
 * Le mécanisme réellement employé, tel que le front l'apprend.
 *
 * Le badge vert « Trousseau » de `A2` serait un mensonge en développement : l'écran doit
 * pouvoir dire la vérité, donc il a besoin de cette information.
 */
export type SecretMechanism = "keychain" | "encryptedFile";

/**
 * Référence vers un secret rangé par `05c` — **jamais sa valeur**.
 *
 * Type distinct plutôt qu'un alias de `String` : une valeur de secret ne peut pas y
 * être affectée par erreur, puisqu'aucune conversion implicite n'existe. Rien à
 * divulguer ici de toute façon, une référence n'est pas un secret.
 */
export type SecretRef = string & { readonly __secretRef: unique symbol };

export type SslMode = "disable" | "allow" | "prefer" | "require" | "verify-ca" | "verify-full";

/**
 * Les trois thèmes du mockup.
 */
export type Theme = "cahier" | "nuit" | "systeme";

/**
 * Le panneau « Proxy / tunnel » de `A2`, tel qu'il est configuré.
 */
export type Tunnel = { 
/**
 * `None` signifie « auto » — le port local est choisi à l'ouverture par `06`.
 *
 * **Hors de `Proxy`, et c'est le point** : il est vrai des deux sortes. Le dupliquer
 * dans chaque variante obligerait chaque lecteur à faire un `match` pour lire une
 * donnée qui ne varie pas.
 */
localPort: number | null, proxy: Proxy, };
