// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSettings, Engine, SslMode } from "./config";
import type { DatabaseKey } from "./engine";

/**
 * Ce que la modale d'export a le droit de dire, et rien d'autre.
 *
 * **Cinq verdicts, pas un booléen.** « Indisponible » recouvre cinq situations, dont deux
 * se ressemblent sans être la même chose : `NotYetSupported` est une promesse à tenir
 * (`16`–`21`), `NoLocalDump` une impossibilité de construction — Snowflake et BigQuery
 * n'ont pas d'outil local, leur export sort vers un stockage cloud, ce qui heurte
 * « aucune ressource réseau ». Les fondre dirait « pas encore » d'un cas qui ne viendra
 * jamais.
 */
export type DumpAvailability = { "kind": "ready", tool: string, version: Version, } | { "kind": "toolMissing", binary: string, } | { "kind": "toolTooOld", tool: Version, server: Version, } | { "kind": "notYetSupported", engine: Engine, } | { "kind": "noLocalDump", engine: Engine, };

/**
 * Ce qu'un échec de dump dit au front.
 *
 * **`kind` en plus du message** : la modale doit pouvoir traiter « tronqué » et « annulé »
 * autrement qu'un échec quelconque, et reconnaître un cas en cherchant un mot dans une
 * phrase française serait un couplage au libellé.
 */
export type DumpFailure = { kind: string, message: string, };

/**
 * La requête d'export ou d'import, telle que le front la fournit.
 */
export type DumpRequest = { key: DatabaseKey, variant: ConnectionSettings, engine: Engine, 
/**
 * Le chemin choisi dans le sélecteur natif — destination à l'export, source à l'import.
 */
file: string, };

/**
 * Le transport **réellement employé** par `pg_dump` et `psql`, tel que la modale l'affiche (#82).
 *
 * C'est une donnée et non un texte : l'écran compose la phrase, et `child_env` en dérive les
 * deux variables. Le mode est celui qui part — `allow` y est donc déjà devenu `prefer`.
 */
export type DumpTransport = { mode: SslMode, root: RootCert, };

/**
 * Ce que la modale reçoit à l'ouverture : le verdict, et le transport **réellement employé**.
 *
 * **Le transport est dit dans la modale** (#82) : l'audit avait trouvé des dumps partis en
 * clair sans que rien ne le signale, et une connexion testée dans `A2` porte déjà sa mention
 * « TLS non vérifié ». `None` quand le moteur n'a pas d'outil local — il n'y a rien à lancer,
 * donc aucun transport à décrire.
 */
export type DumpVerdict = { availability: DumpAvailability, transport: DumpTransport | null, };

/**
 * Ce que la lecture des deux extrémités permet de dire, et rien de plus.
 *
 * **Au-delà de l'en-tête et du pied, rien n'est validé** : le corps est un script SQL
 * arbitraire, et prétendre le vérifier serait mentir.
 */
export type Inspection = { "kind": "pgDump", origine: Version, } | { "kind": "tronque" } | { "kind": "tropRecent", origine: Version, cible: Version, } | { "kind": "etranger" } | { "kind": "vide" } | { "kind": "illisible", cause: string, };

/**
 * Où libpq cherche l'autorité qui vérifie le certificat du serveur.
 */
export type RootCert = { "kind": "unused" } | { "kind": "libpqDefault" } | { "kind": "system" } | { "kind": "file", path: string, };

/**
 * Une version de moteur ou d'outil, réduite à ce dont les règles ont besoin.
 *
 * **La mineure est portée mais ne décide de rien** : elle est affichée dans les messages
 * (« pg_dump 13.14 face à un serveur 17.6 » se lit mieux que « 13 face à 17 »), et
 * mesuré le 19 août 2026, `pg_dump` 17.4 dumpe un serveur 17.6 sans se plaindre. Une
 * règle sur la version complète refuserait donc un cas qui marche.
 */
export type Version = { majeure: number, mineure: number, };
