// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSettings, Engine } from "./config";

/**
 * Ce qu'une application de modifications a produit (`11d`).
 */
export type ApplyOutcome = { 
/**
 * Le nombre de lignes effectivement écrites — une par modification quand tout va bien.
 */
applied: number, 
/**
 * Le SQL qui **défait** ce qui vient d'être fait, à montrer et à copier.
 *
 * Disponible dans la session, pas persisté : `A10` en fait une préférence à 24 h, ce qui
 * suppose de décider où le garder, sous quelle forme, et ce qu'il advient d'un patch dont la
 * base a changé entre-temps. Trois questions qui appartiennent à `15`.
 */
inverseSql: string, };

/**
 * Une colonne, telle que `A9` la tabule et `A5` la liste.
 *
 * **Pas `Eq`** depuis que `frequency` existe : un flottant ne l'est pas — `NaN` n'est égal à rien,
 * pas même à lui-même. `PartialEq` suffit à tout ce que le projet en fait (des `assert_eq!`), et
 * prétendre le contraire serait faux.
 */
export type ColumnInfo = { 
/**
 * Rang, la colonne « # » de `A9`.
 */
position: number, name: string, 
/**
 * Le type tel que le moteur le nomme — `int8`, `bpchar`, `tstz`. `A5` l'affiche tel quel.
 */
typeName: string, category: TypeCategory, nullable: boolean, default: string | null, 
/**
 * `Some` quand la colonne est une identité — `GENERATED ... AS IDENTITY`.
 *
 * **Distinct de `default`**, qui est `NULL` pour ces colonnes : PostgreSQL ne range pas
 * l'identité dans `pg_attrdef`. Sans ce champ, `A9` afficherait « — » dans la colonne
 * « défaut » d'une clé primaire auto-incrémentée, ce qui la ferait lire comme une colonne
 * à remplir soi-même.
 */
identity: Identity | null, key: KeyKind | null, comment: string | null, 
/**
 * La part des documents qui portent ce champ, entre 0 et 1 — **`18d`**.
 *
 * `None` pour un moteur relationnel, et ce n'est pas « inconnu » : une colonne y est
 * **déclarée**, donc elle existe pour toutes les lignes et la question ne se pose pas. `Some`
 * n'a de sens que là où le schéma est déduit d'un échantillon.
 *
 * **Un champ du modèle, pas une décoration de `A8`** : `A9` peut l'afficher pour une
 * collection sans une ligne de code propre à MongoDB, et un champ à moins de 100 % se
 * distingue partout où les colonnes s'affichent.
 */
frequency: number | null, };

/**
 * Le résultat d'un test de connexion, tel que `A2` l'affiche :
 * « Connecté en 240 ms · PostgreSQL 16.2 ».
 *
 * Pas un booléen : « ça marche » sans la latence ni la version ne remplirait pas l'écran.
 */
export type ConnectionProbe = { 
/**
 * Durée jusqu'à une connexion **interrogeable**, aller-retour de version compris —
 * c'est ce que l'utilisateur perçoit.
 */
latencyMs: number, serverVersion: string, };

/**
 * La variante à tester, telle que `A2` la fournit.
 *
 * Le mot de passe est **en clair** et séparé de la variante, à l'inverse de
 * `ConnectionSettings` qui n'en porte qu'une `SecretRef`. C'est délibéré : tester une
 * connexion n'exige pas que l'entité existe, donc aucun secret n'est encore rangé. `08e`
 * fera l'inverse — ranger d'abord, référencer ensuite.
 */
export type ConnectionRequest = { 
/**
 * **Le moteur à interroger, et non celui qu'on suppose.**
 *
 * Il manquait. `tester` appelait `PostgresAdapter` en dur, donc « Tester la connexion »
 * parlait PostgreSQL à un `mongod` : le pilote envoie sa demande de démarrage, le serveur
 * documentaire n'y répond rien qu'il sache lire, et **l'appel reste pendu** — le bouton
 * affichait « Test en cours… » indéfiniment, ce qui se lit exactement comme un clic sans
 * effet. C'est le pire des symptômes possibles : ni verdict, ni échec, ni message.
 *
 * Le moteur est une propriété du brouillon depuis `05a` — l'écran le fait choisir en
 * premier. Il n'y a donc rien à deviner ici, seulement à transmettre.
 */
engine: Engine, variant: ConnectionSettings, password: string | null, };

/**
 * L'état d'une base, tel que l'arbre de `09d` l'affiche.
 *
 * **Quatre états, pas deux.** « Jamais tentée » n'est pas « hors ligne » : les confondre
 * afficherait en rouge une base qu'on n'a simplement pas ouverte. Et l'arbre se lit sans
 * réseau — décision du 7 août 2026 — donc l'état par défaut d'une base est `Jamais`, pas un
 * échec.
 */
export type ConnectionState = { "kind": "never" } | { "kind": "connecting" } | { "kind": "connected", serverVersion: string, 
/**
 * Le port local du tunnel, quand la variante en déclare un.
 */
tunnelLocalPort: number | null, } | { "kind": "offline", reason: string, };

/**
 * Un état de connexion, avec la base qu'il concerne.
 */
export type ConnectionStateEntry = { key: DatabaseKey, state: ConnectionState, };

/**
 * Ce que `A2` affiche après un test réussi.
 *
 * Distinct de `ConnectionProbe` : il porte en plus l'avertissement TLS, qui n'est pas une
 * propriété du serveur mais de **notre implémentation**. Le mêler à la sonde ferait croire
 * que PostgreSQL le rapporte.
 */
export type ConnectionTest = { latencyMs: number, serverVersion: string, 
/**
 * Le port local du tunnel, quand la variante en déclare un. `A2` l'affiche sous
 * « auto (63342) ».
 */
tunnelLocalPort: number | null, 
/**
 * Vrai quand le mode SSL demandé exigeait une vérification que **rien n'a faite**.
 *
 * `06b` emploie encore `NoTls` : un test en `verify-ca` ou `verify-full` réussit sans que
 * l'identité du serveur ait été contrôlée. Afficher « Connecté » serait alors exact et
 * trompeur. Ce drapeau existe pour que `A2` le dise, et **disparaîtra** avec le
 * branchement du TLS — pas avant.
 */
tlsUnverified: boolean, };

export type ConstraintInfo = { name: string, definition: string, };

/**
 * Désigne une base dans un projet, pour un environnement.
 *
 * **Trois chaînes plutôt qu'une clé préformée.** Envoyer `"Halle/analytics/dev"` depuis le
 * front demanderait au JavaScript de connaître la convention de composition, donc de la
 * dupliquer — le même piège que la référence de secret de `08e`, tranché de la même façon.
 */
export type DatabaseKey = { project: string, database: string, environment: string, };

/**
 * Un échec côté moteur.
 *
 * `A7` affiche « le code SQLSTATE et la position » dans son onglet Messages, et `A3` les
 * lignes de journal d'un échec de connexion. Le code est repris **tel quel** : c'est lui
 * qui permet à un écran de distinguer « mauvais mot de passe » (`28P01`) de « base
 * inconnue » (`3D000`) sans analyser une chaîne traduite.
 */
export type EngineError = { 
/**
 * `SQLSTATE` pour PostgreSQL, son équivalent ailleurs. `None` quand l'échec est en
 * amont du moteur — un socket refusé, par exemple.
 */
code: string | null, 
/**
 * Position dans la requête, quand le moteur la donne. `A7` surligne la ligne fautive.
 */
position: number | null, message: string, };

/**
 * Un filtre par en-tête de colonne, tel que `A5` le saisit.
 *
 * La valeur reste une **chaîne** : c'est ce que l'utilisateur a tapé, et c'est
 * l'adaptateur qui la lie en paramètre selon le type de la colonne. La convertir ici
 * exigerait de connaître les types de sept moteurs.
 */
export type Filter = { column: string, operator: FilterOperator, 
/**
 * `None` pour `is null`.
 */
value: string | null, };

/**
 * Les cinq opérateurs du popover de `A5` : `=`, `≠`, `in`, `~`, `is null`.
 */
export type FilterOperator = "eq" | "ne" | "in" | "matches" | "isNull";

/**
 * Les deux formes d'identité de la norme SQL, que PostgreSQL distingue.
 *
 * `Always` refuse une valeur fournie par l'insertion, `ByDefault` l'accepte. La différence est
 * visible à l'écriture, donc elle est dite plutôt que fondue en un booléen.
 */
export type Identity = "always" | "byDefault";

export type IndexInfo = { name: string, 
/**
 * La définition rendue par le moteur, affichée en mono par `A9`. Jamais reconstruite
 * à la main.
 */
definition: string, };

export type KeyKind = "primary" | "foreign";

/**
 * Les compteurs du contrôle segmenté de `A4` : « Tables 8 · Vues 2 · Fonctions 6 ·
 * Index 31 ».
 */
export type ObjectCounts = { tables: number, views: number, functions: number, indexes: number, };

/**
 * La nature d'un objet de schéma. Les quatre que `A4` compte dans son contrôle segmenté.
 */
export type ObjectKind = "table" | "view" | "function" | "index";

/**
 * Une modification en attente, telle que `A6` la retient (`11a`).
 *
 * **La valeur est du texte, ou `None` pour `NULL`.** C'est exactement ce que l'utilisateur a tapé :
 * inventer un type à partir de la chaîne — « 0012 est un nombre » — changerait la valeur avant même
 * de l'écrire. Le littéral produit est cité, et le moteur le convertit vers le type de la colonne.
 */
export type PendingUpdate = { 
/**
 * La valeur de la **clé primaire** de la ligne, en texte — le `WHERE` de l'`UPDATE`.
 *
 * Pas un rang : un rang change au moindre tri, et l'`UPDATE` frapperait une autre ligne
 * (`11a`).
 */
key: string, column: string, 
/**
 * La nouvelle valeur, ou `None` pour `NULL`. La distinction est l'une des rares qu'un client de
 * bases ne doit pas brouiller : une chaîne vide n'est pas `NULL`.
 */
value: string | null, 
/**
 * La valeur **attendue** dans la base — celle qui était affichée quand on a saisi.
 *
 * Elle entre dans le `WHERE` : entre la lecture et l'écriture, quelqu'un d'autre a pu modifier
 * la ligne, et écrire quand même écraserait son travail en silence. Zéro ligne affectée signifie
 * « la valeur a changé sous vos pieds », et toute la transaction est annulée.
 *
 * Plus faible qu'un numéro de version, et c'est ce que le schéma permet : toutes les tables n'en
 * ont pas, et en exiger un réduirait l'édition à celles qui en ont. **Limite connue** : deux
 * modifications successives ramenant la même valeur passeraient inaperçues.
 */
expected: string | null, };

/**
 * Le plan d'exécution d'une requête (`12e`).
 */
export type QueryPlan = { 
/**
 * Le plan tel que le serveur le rend, ligne par ligne.
 */
lines: Array<string>, 
/**
 * Le SQL d'explication réellement envoyé — `explain <requête>`, montré à l'écran.
 */
sql: string, durationMs: number, };

/**
 * Le résultat d'une requête libre de la console (`12c`).
 *
 * **Distinct de `RowWindow`**, qui décrit une fenêtre de lecture d'une table connue : ici les
 * colonnes ne viennent pas du catalogue mais du résultat, et il n'y a ni décalage ni total — une
 * requête arbitraire n'a pas de « page suivante » définissable.
 */
export type QueryResult = { 
/**
 * Les noms des colonnes rendues, dans l'ordre.
 */
columns: Array<string>, rows: Array<Array<Value>>, 
/**
 * Le SQL **réellement exécuté**, limite comprise s'il y en a une.
 *
 * Montré à l'écran : une requête affichée différente de celle qui a tourné serait un piège pour
 * qui débogue — le même arbitrage que `RowWindow.sql` en `10c`.
 */
sql: string, durationMs: number, 
/**
 * La limite que **DoraBase** a ajoutée, quand la requête n'en portait pas.
 *
 * **Annoncée, jamais silencieuse.** Une limite tue ferait croire à une table de mille lignes —
 * un mensonge sur les données, la pire catégorie de défaut pour cet outil.
 */
appliedLimit: number | null, };

/**
 * Une clé étrangère, dans un sens ou dans l'autre.
 *
 * `A4` montre un bloc « Relations » ; `A5` un aperçu de « ligne liée ». Les deux sens
 * sont nécessaires : sortant pour suivre une référence, entrant pour savoir qui référence
 * cette table.
 */
export type Relation = { constraintName: string, direction: RelationDirection, columns: Array<string>, targetSchema: string, targetTable: string, targetColumns: Array<string>, };

export type RelationDirection = "outgoing" | "incoming";

/**
 * Un comptage de lignes, avec sa fiabilité.
 *
 * `A4` affiche « 1.9 M » — une estimation que le planificateur maintient à coût nul.
 * `A9` affiche « 1 904 220 » — un compte exact, qui exige un parcours complet. Sans la
 * distinction, l'écran ne saurait pas s'il montre une valeur sûre, et la colonne
 * « Dernier ANALYZE » de `A4` n'aurait aucun sens.
 */
export type RowCount = { "kind": "estimated", value: number, } | { "kind": "exact", value: number, } | { "kind": "unknown" };

/**
 * Les paliers de `LIMIT` du stepper de `A5` : 100 / 500 / 1000 / 5000.
 *
 * Une énumération, **pas un `u32`** : c'est ce qui empêche un appelant de demander cinq
 * millions de lignes, et donc ce qui rend la contrainte IPC vérifiable par le compilateur
 * au lieu de reposer sur la discipline.
 */
export type RowLimit = "oneHundred" | "fiveHundred" | "oneThousand" | "fiveThousand";

/**
 * L'intention d'une lecture, que l'adaptateur traduit en SQL paramétré.
 */
export type RowQuery = { schema: string, table: string, filters: Array<Filter>, sort: Array<SortKey>, offset: number, 
/**
 * Toujours présente, et prise dans un ensemble fermé.
 */
limit: RowLimit, };

/**
 * Une fenêtre de lignes — jamais un jeu complet.
 */
export type RowWindow = { offset: number, rows: Array<Array<Value>>, 
/**
 * Le total, **quand il est connu**. Optionnel délibérément : le compter exactement
 * sur une grande table coûte un parcours complet, et `A5` affiche de toute façon le
 * compte de la fenêtre.
 */
total: RowCount | null, 
/**
 * Le SQL réellement exécuté, que `A5` montre derrière « Voir le SQL ».
 */
sql: string, 
/**
 * Durée de la requête, pour la barre d'état de `A5` (« 41 ms »).
 */
durationMs: number, };

export type SchemaInfo = { name: string, counts: ObjectCounts, };

export type SortDirection = "ascending" | "descending";

/**
 * Un critère de tri. `A5` en accepte plusieurs, numérotés — leur ordre dans le vecteur
 * **est** leur rang.
 */
export type SortKey = { column: string, direction: SortDirection, };

/**
 * Tout ce que `A9` affiche d'une table, DDL compris.
 *
 * **Pas `Eq`**, parce qu'il contient des `ColumnInfo` — voir leur documentation.
 */
export type TableDetail = { schema: string, name: string, rows: RowCount, sizeBytes: number | null, comment: string | null, columns: Array<ColumnInfo>, indexes: Array<IndexInfo>, constraints: Array<ConstraintInfo>, triggers: Array<TriggerInfo>, relations: Array<Relation>, 
/**
 * Le `CREATE TABLE` de `A9`, assemblé depuis ce que le catalogue rend déjà formaté.
 */
ddl: string, };

/**
 * Une ligne du tableau d'objets de `A4` : « Nom, Lignes, Taille, Col., Clé primaire,
 * Dernier ANALYZE, Commentaire ».
 */
export type TableSummary = { name: string, kind: ObjectKind, rows: RowCount, 
/**
 * `None` quand le moteur ne sait pas donner de taille physique.
 */
sizeBytes: number | null, columnCount: number, primaryKey: string | null, 
/**
 * Quand l'estimation de `rows` a été rafraîchie — c'est ce qui dit à quel point s'y
 * fier. `A4` en fait une colonne.
 */
lastAnalyze: string | null, comment: string | null, };

export type TriggerInfo = { name: string, definition: string, };

/**
 * La catégorie d'un type de colonne, indépendante du moteur.
 *
 * `A5` affiche un glyphe par catégorie (`T`, `#`, `⏱`, `{}`, `ID`) et aligne les nombres
 * et les dates différemment. Dériver la catégorie dans l'écran obligerait chaque écran à
 * connaître les types de sept moteurs ; c'est donc l'adaptateur qui la détermine.
 */
export type TypeCategory = "text" | "number" | "timestamp" | "json" | "uuid" | "boolean" | "binary" | "other";

/**
 * Ce qu'il faut pour prévisualiser — ou plus tard exécuter — une suite de modifications.
 */
export type UpdatePlan = { schema: string, table: string, 
/**
 * La colonne qui identifie une ligne. **Fournie par l'écran**, qui la connaît par
 * l'introspection : la redemander à la base à chaque prévisualisation coûterait un
 * aller-retour pour une information déjà affichée.
 */
keyColumn: string, changes: Array<PendingUpdate>, };

/**
 * Une valeur de cellule, **typée** et non préformatée.
 *
 * `A5` rend `NULL` distinctement, aligne nombres et dates en mono, et met certaines
 * colonnes en pastille. C'est donc l'écran qui formate — lui seul connaît la densité et
 * la locale. Rendre une chaîne déjà formatée lui retirerait cette décision.
 */
export type Value = { "kind": "null" } | { "kind": "bool", value: boolean, } | { "kind": "int", value: number, } | { "kind": "float", value: number, } | { "kind": "decimal", value: string, } | { "kind": "text", value: string, } | { "kind": "timestamp", value: string, } | { "kind": "json", value: string, } | { "kind": "binary", base64: string, };
