// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSettings, Engine, InstanceId, ManagedInstance } from "./config";

/**
 * Un geste, et le droit qu'a ce compte de le faire.
 *
 * # Pourquoi le cœur répond à cette question, plutôt que l'écran ne devine
 *
 * Le ticket le pose en toutes lettres : DoraBase lit `pg_roles` à l'ouverture et **nomme les gestes
 * que ce compte n'a pas le droit de faire**, plutôt que de laisser les boutons échouer. Un bouton
 * qui part et revient avec « permission denied for database » est le défaut n° 36 avec un aller-
 * retour en plus : on apprend l'interdit *après* avoir agi, et sur un serveur de production.
 *
 * **`reason` est portée, jamais reconstruite à l'écran.** C'est elle qui remplit le `title` d'un
 * contrôle désactivé, et elle nomme l'attribut qui manque — « le rôle n'a pas CREATEDB » — non un
 * « action indisponible » qui n'apprend rien.
 */
export type Capability = { gesture: InstanceGesture, allowed: boolean, 
/**
 * Pourquoi ce geste est refusé. `None` quand il est permis.
 */
reason: string | null, };

/**
 * Les trois privilèges de niveau base. Fermés : `has_database_privilege` n'en connaît pas d'autres.
 */
export type DatabasePrivilege = "create" | "temporary" | "connect";

/**
 * Ce qu'un retrait rend.
 */
export type DeleteInstanceResult = { instances: Array<ManagedInstance>, 
/**
 * Vrai quand un mot de passe n'a **pas** pu être retiré du magasin. L'écran le dit ; le retrait,
 * lui, a bien eu lieu.
 */
secretResiduel: boolean, };

/**
 * Ce qu'on demande à une instance de faire.
 *
 * # Une énumération portée par l'IPC, et non une chaîne de SQL
 *
 * L'écran n'envoie **jamais** de SQL. C'est le cœur qui le compose, à partir d'un geste nommé et de
 * ses paramètres, et qui le rend pour que la confirmation le montre. L'inverse — le front compose,
 * le cœur exécute — mettrait la citation des identifiants et le choix entre `RESTRICT` et `CASCADE`
 * dans l'écran, c'est-à-dire hors de portée des tests du cœur et à la merci d'un nom de rôle
 * contenant un guillemet.
 *
 * C'est la règle que `row_as_insert` et `preview_updates` posent déjà : ce qui demande de connaître
 * les règles du moteur appartient à l'adaptateur.
 */
export type InstanceAction = { "kind": "createDatabase", name: string, 
/**
 * `None` laisse le propriétaire par défaut, qui est le rôle courant.
 */
owner: string | null, } | { "kind": "alterDatabaseOwner", name: string, owner: string, } | { "kind": "dropDatabase", name: string, } | { "kind": "createRole", name: string, attributes: RoleAttributes, 
/**
 * Le mot de passe, quand le formulaire en porte un — **le vérificateur SCRAM, jamais la
 * saisie**. Voir `RoleAttributes` et `postgres::scram`.
 */
verifier: string | null, } | { "kind": "alterRole", name: string, attributes: RoleAttributes, 
/**
 * Idem, et `None` **laisse le mot de passe en place**.
 *
 * C'est la règle du champ vide de `mettre_a_jour`, appliquée ici : corriger un attribut ne
 * doit pas obliger à retaper un mot de passe, et l'oublier ne doit pas l'effacer. Rien dans
 * le SQL composé ne le mentionne alors — un `PASSWORD NULL` retirerait le mot de passe.
 */
verifier: string | null, } | { "kind": "dropRole", name: string, reassignTo: string, } | { "kind": "grantDatabase", role: string, database: string, privilege: DatabasePrivilege, } | { "kind": "revokeDatabase", role: string, database: string, privilege: DatabasePrivilege, } | { "kind": "terminateSession", pid: number, } | { "kind": "createExtension", name: string, } | { "kind": "dropExtension", name: string, } | { "kind": "setParameter", name: string, value: string, } | { "kind": "resetParameter", name: string, };

/**
 * Une base de l'instance — la section « Bases ».
 */
export type InstanceDatabase = { name: string, owner: string, encoding: string, collation: string, 
/**
 * `None` quand le rôle ne peut pas la mesurer — voir `InstanceOverview::total_size_bytes`.
 */
sizeBytes: number | null, 
/**
 * Les sessions ouvertes sur cette base.
 */
connections: number, 
/**
 * Un modèle (`template0`, `template1`) : il se liste, mais ne se supprime pas.
 */
isTemplate: boolean, 
/**
 * `datallowconn` : une base qui refuse les connexions.
 */
allowConnections: boolean, };

/**
 * Une extension — la section « Extensions ».
 */
export type InstanceExtension = { name: string, 
/**
 * La version en place, ou `None` : l'extension est **disponible** mais pas installée.
 */
installedVersion: string | null, 
/**
 * La version que le serveur installerait.
 */
defaultVersion: string | null, 
/**
 * La base où la lecture a eu lieu.
 *
 * # Pourquoi une seule base, et pourquoi la colonne existe quand même
 *
 * `pg_extension` est un catalogue **par base** : une extension installée dans `analytics` ne
 * paraît pas dans `postgres`. Les lire toutes demanderait une connexion par base — donc une
 * poignée de main, un tunnel, et un refus pour chaque base où le rôle n'a pas `CONNECT`, sur
 * une section qu'on ouvre en passant.
 *
 * La lecture porte donc sur la **base de service** de l'instance, celle du formulaire, et cette
 * colonne la nomme. C'est l'honnêteté des deux nombres de la barre d'état du diagramme, sur une
 * autre affirmation : une section « Extensions » qui tairait sa portée se lirait comme la liste
 * des extensions du serveur, ce qu'elle n'est pas.
 */
database: string, schema: string | null, };

/**
 * Les gestes que le gestionnaire propose. Une énumération **fermée** : un geste qui n'y est pas
 * n'est pas exprimable, donc pas exécutable.
 */
export type InstanceGesture = "createDatabase" | "alterDatabase" | "dropDatabase" | "createRole" | "alterRole" | "dropRole" | "grantPrivilege" | "terminateSession" | "createExtension" | "dropExtension" | "setParameter";

/**
 * Avec quoi on est connecté — le bloc que la vue d'ensemble affiche sous les tuiles.
 *
 * **Rendu par le cœur et non recomposé par l'écran**, bien que l'écran connaisse la déclaration :
 * `role` est ce que `current_user` répond, qui n'est pas forcément l'utilisateur déclaré — `SET
 * ROLE`, un `pg_hba` en `map=`, une authentification IAM. Et `tls` dit ce que la session **est**,
 * non ce que le formulaire a demandé : un `prefer` qui a replié en clair afficherait « chiffré »
 * si on lisait le réglage.
 */
export type InstanceIdentity = { 
/**
 * L'hôte et le port **effectivement joints** : `127.0.0.1` et le port local quand un proxy
 * s'interpose, comme le dump le fait déjà. Mentir ici enverrait chercher une panne réseau là
 * où c'est le tunnel qui parle.
 */
host: string, port: number, 
/**
 * Le rôle de la session — `current_user`.
 */
role: string, 
/**
 * La base de service à laquelle on est connecté.
 */
database: string, 
/**
 * Vrai quand la session est chiffrée, lu dans `pg_stat_ssl` pour notre propre backend.
 */
tls: boolean, 
/**
 * Le chiffre de la session, quand il y en a un — « TLSv1.3 / TLS_AES_256_GCM_SHA384 ».
 */
tlsCipher: string | null, 
/**
 * Où le mot de passe est rangé : « Trousseau » ou « fichier chiffré ».
 *
 * **Le mécanisme, jamais le secret ni sa référence.** C'est le badge que `A2` affiche déjà, et
 * la question à laquelle il répond est « puis-je me fier à ce rangement ? ».
 */
secretLocation: string | null, };

/**
 * Ce qu'une exécution rend.
 */
export type InstanceOutcome = { 
/**
 * Les ordres réellement exécutés — **les mêmes** que ceux du plan.
 */
statements: Array<string>, 
/**
 * Une phrase qui dit ce qui s'est passé, dans les termes du geste.
 */
message: string, };

/**
 * Les six tuiles de la vue d'ensemble, plus l'identité de la connexion.
 *
 * **Un seul aller-retour pour toute la section**, et non une commande par tuile : elles décrivent
 * le même instant, et six lectures successives afficheraient six instants voisins — un compte de
 * connexions relevé avant les bases, une taille relevée après. La barre annonce « relevé il y a
 * 12 s » ; cette phrase n'est vraie que si tout vient du même relevé.
 */
export type InstanceOverview = { 
/**
 * « PostgreSQL 17.6 », abrégée comme partout ailleurs dans le produit.
 */
serverVersion: string, 
/**
 * Depuis combien de temps le serveur tourne.
 *
 * `None` quand le serveur ne le dit pas : `pg_postmaster_start_time()` demande un droit que
 * tous les rôles n'ont pas. Un zéro y serait un mensonge — « démarré à l'instant » — là où un
 * tiret dit « nous ne savons pas », la distinction que `RowCount::Unknown` a déjà coûtée une
 * fois.
 */
uptimeSeconds: number | null, 
/**
 * Les connexions ouvertes **sur tout le serveur**, et le plafond de `max_connections`.
 */
connections: number, maxConnections: number, databases: number, roles: number, 
/**
 * La somme des tailles des bases, quand elles sont toutes mesurables.
 *
 * `None` dès qu'une base refuse `pg_database_size` — ce qui arrive à un rôle non
 * superutilisateur sur une base dont il n'a pas `CONNECT`. **Une somme partielle serait pire
 * qu'aucune** : elle s'afficherait comme la taille de l'instance en en taisant une part.
 */
totalSizeBytes: number | null, 
/**
 * L'identité de la connexion, telle que la vue d'ensemble l'affiche.
 */
identity: InstanceIdentity, 
/**
 * Ce que ce compte a le droit de faire, geste par geste.
 */
capabilities: Array<Capability>, };

/**
 * Le SQL d'un geste, **avant** de partir.
 *
 * # Ce que porte `note`, et pourquoi ce n'est pas dans le SQL
 *
 * La confirmation montre les ordres dans l'ordre où ils partent, et une ligne sous l'encart dit ce
 * que le SQL **ne dit pas** : pourquoi trois ordres pour supprimer un rôle, pourquoi `RESTRICT` et
 * non `CASCADE`, que `REASSIGN OWNED` se rejoue base par base. Un commentaire SQL l'aurait dit
 * *dans* l'encart, donc dans ce qui part — et le premier lecteur à copier le bloc pour le rejouer
 * dans `psql` aurait emporté nos explications avec.
 */
export type InstancePlan = { 
/**
 * Les ordres, dans l'ordre d'exécution. Ce qui est affiché **est** ce qui part.
 */
statements: Array<string>, 
/**
 * Ce que le SQL ne dit pas. Vide quand il n'y a rien à ajouter.
 */
note: string, 
/**
 * Vrai quand le geste retire quelque chose : le bouton d'exécution passe en `--danger`.
 */
destructive: boolean, };

/**
 * Une cellule de la matrice rôle × base — la section « Privilèges ».
 *
 * **Trois booléens et non une chaîne « CTc »**, bien que ce soit ce que la cellule affiche : la
 * composition du sigle appartient à l'écran, et un `grant` porte sur **un** privilège. Rendre la
 * chaîne obligerait le front à la défaire pour savoir quoi révoquer.
 */
export type InstancePrivilege = { role: string, database: string, 
/**
 * `CREATE` — créer un schéma dans cette base.
 */
create: boolean, 
/**
 * `TEMPORARY` — y créer des tables temporaires.
 */
temporary: boolean, 
/**
 * `CONNECT` — s'y connecter, sans quoi les deux autres ne servent à rien.
 */
connect: boolean, };

/**
 * Un rôle du serveur — la section « Utilisateurs ».
 *
 * **« Rôle » et non « utilisateur », dans le modèle.** PostgreSQL n'a que des rôles depuis la 8.1 ;
 * un « utilisateur » y est exactement un rôle avec `LOGIN`. Le nommer autrement dans le code aurait
 * fait chercher une notion qui n'existe pas dans le catalogue. L'écran, lui, garde le mot de la
 * maquette pour son titre de section — c'est celui qu'on cherche.
 */
export type InstanceRole = { name: string, 
/**
 * `rolcanlogin` : ce qui décide de l'icône `key` plutôt que `lock`.
 */
canLogin: boolean, superuser: boolean, createDb: boolean, createRole: boolean, replication: boolean, bypassRls: boolean, 
/**
 * `rolvaliduntil`, en texte : rien ne calcule dessus, et le formatage appartient à l'écran, qui
 * seul connaît la locale. C'est la règle des horodatages de l'introspection.
 */
validUntil: string | null, 
/**
 * Les rôles dont celui-ci est membre — la colonne « membre de ».
 */
memberOf: Array<string>, 
/**
 * Le nombre de bases dont ce rôle est **propriétaire**.
 *
 * C'est ce que la colonne « bases » dit, et c'est le nombre qui compte avant de supprimer :
 * un rôle qui possède des bases ne se supprime pas sans les réattribuer, et c'est exactement ce
 * que le `REASSIGN OWNED` de la confirmation fait.
 */
ownedDatabases: number, 
/**
 * Un rôle du système (`pg_read_all_data`, `pg_monitor`…), que le catalogue livre avec le
 * serveur.
 *
 * **Listé et marqué, jamais tu** : c'est l'arbitrage des schémas de catalogue d'`API-33`. Ils
 * existent, ils apparaissent dans les privilèges, et ne pas les montrer ferait chercher d'où
 * vient un droit. Ce sont eux, en revanche, que la suppression refuse.
 */
system: boolean, };

/**
 * Une session ouverte — la section « Sessions ».
 */
export type InstanceSession = { pid: number, 
/**
 * `None` pour un processus interne du serveur — l'autovacuum, le writer — qui n'a pas de rôle.
 */
user: string | null, database: string | null, 
/**
 * L'adresse du client, ou « local » pour une connexion par socket unix.
 */
client: string, 
/**
 * **Qui a ouvert cette session**, autant que le serveur puisse le dire (9 septembre 2026, à la
 * demande).
 *
 * # Ce que ce champ est, et ce qu'il ne peut pas être
 *
 * Le PID de `pg_stat_activity` est celui du **backend serveur** — le processus que PostgreSQL a
 * forké pour servir la connexion —, jamais celui du client. Il n'existe donc **aucun moyen**,
 * depuis le serveur, de remonter au processus qui s'est connecté : il tourne le plus souvent
 * sur une autre machine, et rien dans le protocole ne transporte son identité système.
 *
 * Ce que le serveur sait est ce que le client **déclare** de lui-même : `application_name`,
 * posé par `psql`, `pgAdmin`, un pilote JDBC, ou DoraBase. C'est la réponse pratique à « qui a
 * ouvert cette connexion », et c'est la seule qui ne soit pas une invention.
 *
 * Pour un processus **interne** du serveur — l'autovacuum, le writer, le checkpointer — il n'y
 * a pas de client à nommer : `backend_type` prend alors le relais et dit lequel c'est. Sans
 * lui, la ligne d'un `autovacuum launcher` n'aurait ni utilisateur, ni base, ni nom : trois
 * tirets et un PID.
 *
 * `None` quand ni l'un ni l'autre ne dit rien — un client qui n'a pas posé de nom sur un
 * serveur antérieur à la 10. La colonne y met le tiret cadratin : « nous ne savons pas » n'est
 * pas « personne ».
 */
process: string | null, 
/**
 * `active`, `idle`, `idle in transaction`… tel que `pg_stat_activity` le dit.
 */
state: string | null, 
/**
 * Depuis combien de temps la session est dans cet état.
 */
durationSeconds: number | null, 
/**
 * Vrai pour **notre propre** session.
 *
 * **Le cœur le dit, l'écran ne le devine pas.** Comparer des PID côté front demanderait de lui
 * envoyer le nôtre, donc une seconde vérité ; et c'est cette ligne-là qu'il ne faut pas
 * proposer de terminer — se couper la branche à laquelle on est assis fermerait l'écran qui
 * vient d'exécuter l'ordre.
 */
isSelf: boolean, };

/**
 * Un paramètre de configuration — la section « Paramètres ».
 */
export type InstanceSetting = { name: string, value: string, unit: string | null, 
/**
 * `internal`, `postmaster`, `sighup`, `superuser`, `user`… : ce qui décide si un changement
 * demande un redémarrage, et si ce rôle peut le faire.
 */
context: string, 
/**
 * D'où vient la valeur : `default`, `configuration file`, `override`…
 */
source: string, 
/**
 * `pending_restart` : la valeur a été changée et n'aura d'effet qu'au redémarrage.
 */
pendingRestart: boolean, 
/**
 * Vrai quand `ALTER SYSTEM SET` a un sens pour ce paramètre.
 *
 * **Faux pour un `internal`**, que le serveur calcule à la compilation (`block_size`,
 * `segment_size`) : le proposer donnerait un champ qui échoue toujours.
 */
settable: boolean, };

/**
 * Les attributs d'un rôle qu'un `CREATE`/`ALTER ROLE` pose.
 *
 * **Une structure et non six paramètres**, parce que `AlterRole` les pose *tous* à chaque fois :
 * PostgreSQL n'a pas de « laisser inchangé » dans `ALTER ROLE`, et un formulaire qui n'enverrait
 * que ce qui a changé demanderait de savoir ce qui était là — donc de relire, donc d'écraser ce
 * qu'un autre aurait changé entre-temps.
 */
export type RoleAttributes = { canLogin: boolean, superuser: boolean, createDb: boolean, createRole: boolean, };

/**
 * Ce que la modale de déclaration envoie.
 *
 * **Le mot de passe est en clair et séparé**, comme dans `SaveDatabaseRequest` : aucune `SecretRef`
 * n'existe avant que le secret soit rangé, et c'est le travail de `config::declarer`.
 */
export type SaveInstanceRequest = { 
/**
 * `None` déclare une instance neuve ; `Some` modifie celle-là.
 */
id: InstanceId | null, label: string, engine: Engine, connection: ConnectionSettings, production: boolean, confirmWrites: boolean, 
/**
 * `None` laisse le mot de passe en place — un champ vide veut dire « inchangé ».
 */
password: string | null, };
