// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce que le fichier porte des mots de passe, tel que son en-tête l'annonce.
 *
 * **Recalculé à la lecture, jamais cru sur parole** — voir [`lire`]. Un en-tête faux est pire qu'un
 * en-tête absent : c'est celui-là qu'on croit, et un fichier édité à la main pourrait annoncer
 * « aucun » en portant des mots de passe.
 */
export type CarriedSecrets = "none" | "embedded";

/**
 * Ce qu'un export a écrit, tel que la modale le rend.
 */
export type ExportReport = { projects: number, connections: number, consoles: number, 
/**
 * Les mots de passe effectivement écrits. `0` quand la case n'était pas cochée.
 */
passwordsCarried: number, 
/**
 * Les connexions qui déclarent un mot de passe dont le magasin n'a **rien** à rendre —
 * `base (env)`. Vide quand la case n'était pas cochée : rien n'était demandé, rien ne manque.
 *
 * **Une absence, jamais une panne.** Un magasin qui *refuse* fait échouer l'export entier :
 * confondre les deux ferait ressaisir un mot de passe déjà rangé, et c'est la distinction que
 * `SecretStore::retrieve` porte depuis `05c`.
 */
passwordsMissing: Array<string>, };

/**
 * Ce qu'un import ferait, ou a fait — **le même calcul dans les deux cas** (voir [`fusionner`]).
 */
export type ImportReport = { 
/**
 * La version de format que le fichier déclare. Une antérieure a été **migrée** à la lecture ;
 * la modale l'affiche pour que « ce fichier vient d'une vieille version » ne soit pas à devenir.
 */
version: number, secrets: CarriedSecrets, 
/**
 * Un sort par projet du fichier, dans l'ordre du fichier.
 */
projects: Array<ProjectOutcome>, };

/**
 * Le détail de ce qu'un projet apporte, et de ce qu'il n'apporte pas.
 *
 * **Dix listes plutôt qu'un compte**, et c'est délibéré : un import amputé en silence se lirait
 * comme un import complet, ce qui est le pire défaut que ce geste puisse avoir. Chacune répond à une
 * question qu'on se pose vraiment devant le fichier de quelqu'un d'autre — qu'est-ce qui arrive,
 * qu'est-ce que je garde, qu'est-ce qu'il me reste à faire.
 */
export type ProjectOutcome = { name: string, verdict: ProjectVerdict, 
/**
 * Les identifiants d'environnement que la fusion déclare en plus.
 */
environmentsAdded: Array<string>, 
/**
 * Les identifiants déjà déclarés ici : **la déclaration locale est gardée**, libellé, couleur
 * et drapeau de production compris.
 *
 * **Garder plutôt qu'écraser, et la raison n'est pas la simplicité** : `production` gouverne
 * les garde-fous d'écriture. Reprendre la valeur du fichier pourrait *lever* un garde-fou que
 * quelqu'un avait posé sur cette machine, en silence et sans qu'il l'ait demandé. Dans ce sens,
 * l'import ne peut jamais affaiblir ce qui est déjà là.
 */
environmentsKept: Array<string>, 
/**
 * Les connexions ajoutées — `base (env)`.
 */
connectionsAdded: Array<string>, 
/**
 * Les connexions déjà déclarées ici : leurs réglages sont **gardés**, jamais écrasés.
 *
 * Leurs consoles, elles, sont versées quand même : c'est tout l'intérêt du geste — recevoir
 * les requêtes de quelqu'un sur une base qu'on a déjà. Ce qu'on refuse d'écraser, ce sont les
 * réglages, parce qu'ils décrivent *comment joindre un serveur* : les reprendre pourrait
 * repointer en silence une connexion vers un autre hôte.
 */
connectionsKept: Array<string>, 
/**
 * Les connexions que rien ne peut accueillir : leur environnement n'est déclaré ni par le
 * fichier ni ici. Elles seraient invisibles dans l'arbre, qui liste les connexions sous le
 * nœud de leur environnement.
 */
connectionsRejected: Array<string>, 
/**
 * Les consoles ajoutées — `base (env) › console`.
 */
consolesAdded: Array<string>, 
/**
 * Les consoles homonymes dans leur connexion : **refusées**, le texte local est gardé.
 */
consolesKept: Array<string>, 
/**
 * Les connexions dont le mot de passe arrive avec le fichier.
 */
passwordsStored: Array<string>, 
/**
 * Les connexions ajoutées qui **attendent** leur mot de passe.
 *
 * À dire, faute de quoi la première ouverture échouerait sur le message du serveur — « password
 * authentication failed » —, qui accuse un mot de passe faux là où il n'y en a aucun.
 */
passwordsMissing: Array<string>, 
/**
 * Les chemins locaux que les connexions ajoutées portent — fichier SQLite, certificat
 * d'autorité, clé privée d'un bastion, kubeconfig. `base (env) : chemin`.
 *
 * Ils voyagent **tels quels** : ce sont des réglages, donc l'intention de quelqu'un, et les
 * réécrire ou les vider serait pire. Mais ils décrivent une autre machine, donc l'import le
 * **dit** plutôt que de laisser le découvrir sur un « fichier introuvable ».
 */
localPaths: Array<string>, };

/**
 * Le sort d'un projet du fichier.
 */
export type ProjectVerdict = { "kind": "created" } | { "kind": "merged" } | { "kind": "skipped" } | { "kind": "rejected", reason: string, };
