// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce que le fichier porte des mots de passe, tel que son en-tête l'annonce.
 *
 * **Sorti de `transfert.rs` par #165**, qui retire ce module du build jusqu'à #169 : le contrat de
 * l'import en a besoin, et sa projection reste dans `transfert.ts`, à la même place, pour que rien
 * ne bouge côté écran. #169 le fera employer par `transfert.rs` d'ici plutôt que de le redéclarer.
 *
 * **Recalculé à la lecture, jamais cru sur parole** : un en-tête faux est pire qu'un en-tête
 * absent.
 */
export type CarriedSecrets = "none" | "embedded";
