import { render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import type { ReactElement } from 'react'
import { describe, expect, it, vi } from 'vitest'
import type { ColumnInfo, TableDetail } from '../../domain/engine'
import { LanguageProvider } from '../../i18n/LanguageContext'
import { DdlPanel } from './DdlPanel'

// Le DDL a quitté `StructureView` pour la colonne de droite (`22`). Ses quatre mesures l'ont suivi
// telles quelles : ce qui a changé est **où** il est rendu, pas ce qu'il doit dire.

function colonne(partiel: Partial<ColumnInfo>): ColumnInfo {
  return {
    position: 1,
    name: 'id',
    typeName: 'bigint',
    category: 'number',
    nullable: false,
    default: null,
    identity: null,
    key: null,
    comment: null,
    frequency: null,
    ...partiel,
  }
}

const DETAIL: TableDetail = {
  schema: 'public',
  name: 'orders',
  rows: { kind: 'estimated', value: 1904220 },
  sizeBytes: 2_100_000_000,
  comment: null,
  columns: [
    colonne({ position: 1, name: 'id', identity: 'byDefault', key: 'primary' }),
    colonne({ position: 2, name: 'user_id', key: 'foreign' }),
    colonne({
      position: 3,
      name: 'created_at',
      typeName: 'timestamptz',
      category: 'timestamp',
      default: 'now()',
    }),
    colonne({ position: 4, name: 'note', typeName: 'text', category: 'text', nullable: true }),
  ],
  indexes: [
    {
      name: 'orders_pkey',
      definition: 'CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id)',
    },
    {
      name: 'orders_created_idx',
      definition: 'CREATE INDEX orders_created_idx ON public.orders USING btree (created_at DESC)',
    },
  ],
  constraints: [{ name: 'orders_total_chk', definition: 'CHECK ((total_cents >= 0))' }],
  triggers: [
    {
      name: 'trg_touch_updated',
      definition:
        'CREATE TRIGGER trg_touch_updated BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION touch()',
    },
  ],
  relations: [
    {
      constraintName: 'orders_user_fk',
      direction: 'outgoing',
      cardinality: 'many',
      columns: ['user_id'],
      targetSchema: 'public',
      targetTable: 'users',
      targetColumns: ['id'],
    },
  ],
  ddl: 'CREATE TABLE public.orders (\n    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL\n);',
  wordSimilarity: false,
}

function monter(ui: ReactElement) {
  return render(<LanguageProvider preferences={{ language: 'fr' }}>{ui}</LanguageProvider>)
}

describe('DdlPanel', () => {
  it('dit que le DDL est reconstruit, pas le texte d’origine', () => {
    monter(<DdlPanel detail={DETAIL} schema="public" />)
    const panneau = screen.getByRole('complementary', { name: /DDL de public\.orders/ })
    // Sans cette phrase, un écart avec le fichier de migration se lit comme une régression.
    // `toBeVisible` et non `toBeInTheDocument` : un `hidden` posé par erreur laisse le texte dans
    // le document. C'est le sabotage qui l'a montré — la première version de ce test passait avec
    // la mention masquée.
    expect(within(panneau).getByText(/Reconstruit depuis le catalogue/)).toBeVisible()
  })

  it('copie le DDL entier, pas le texte visible', async () => {
    const utilisateur = userEvent.setup()
    const writeText = vi.fn(async () => {})
    // `navigator.clipboard` n'a qu'un accesseur sous jsdom : `Object.assign` échoue, il faut
    // redéfinir la propriété.
    Object.defineProperty(navigator, 'clipboard', { value: { writeText }, configurable: true })
    monter(<DdlPanel detail={DETAIL} schema="public" />)

    await utilisateur.click(screen.getByRole('button', { name: 'Copier' }))

    expect(writeText).toHaveBeenCalledWith(DETAIL.ddl)
  })

  it('« Ouvrir dans la console » reste désactivé avec sa raison quand aucune base n’est ouverte', () => {
    monter(<DdlPanel detail={DETAIL} schema="public" />)
    const bouton = screen.getByRole('button', { name: /Ouvrir dans la console/ })
    expect(bouton).toHaveAttribute('aria-disabled', 'true')
    expect(bouton).toHaveAttribute('title', expect.stringContaining('Aucune base ouverte'))
  })

  it('passe le DDL à la console quand elle est disponible', async () => {
    const utilisateur = userEvent.setup()
    const ouvrir = vi.fn()
    monter(<DdlPanel detail={DETAIL} schema="public" onOuvrirDansLaConsole={ouvrir} />)

    await utilisateur.click(screen.getByRole('button', { name: /Ouvrir dans la console/ }))

    expect(ouvrir).toHaveBeenCalledWith(DETAIL.ddl)
  })
})
