import { render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import type { ReactElement } from 'react'
import { describe, expect, it } from 'vitest'
import type { ColumnInfo, TableDetail } from '../../domain/engine'
import { LanguageProvider } from '../../i18n/LanguageContext'
import { momentDuDeclencheur, resumeDIndex, StructureView } from './StructureView'

function colonne(partiel: Partial<ColumnInfo>): ColumnInfo {
  return {
    position: 1,
    name: 'id',
    typeName: 'bigint',
    category: 'number',
    nullable: false,
    default: null,
    identity: null,
    key: null,
    comment: null,
    frequency: null,
    ...partiel,
  }
}

const DETAIL: TableDetail = {
  schema: 'public',
  name: 'orders',
  rows: { kind: 'estimated', value: 1904220 },
  sizeBytes: 2_100_000_000,
  comment: null,
  columns: [
    colonne({ position: 1, name: 'id', identity: 'byDefault', key: 'primary' }),
    colonne({ position: 2, name: 'user_id', key: 'foreign' }),
    colonne({
      position: 3,
      name: 'created_at',
      typeName: 'timestamptz',
      category: 'timestamp',
      default: 'now()',
    }),
    colonne({ position: 4, name: 'note', typeName: 'text', category: 'text', nullable: true }),
  ],
  indexes: [
    {
      name: 'orders_pkey',
      definition: 'CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id)',
    },
    {
      name: 'orders_created_idx',
      definition: 'CREATE INDEX orders_created_idx ON public.orders USING btree (created_at DESC)',
    },
  ],
  constraints: [{ name: 'orders_total_chk', definition: 'CHECK ((total_cents >= 0))' }],
  triggers: [
    {
      name: 'trg_touch_updated',
      definition:
        'CREATE TRIGGER trg_touch_updated BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION touch()',
    },
  ],
  relations: [
    {
      constraintName: 'orders_user_fk',
      direction: 'outgoing',
      cardinality: 'many',
      columns: ['user_id'],
      targetSchema: 'public',
      targetTable: 'users',
      targetColumns: ['id'],
    },
  ],
  ddl: 'CREATE TABLE public.orders (\n    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL\n);',
  wordSimilarity: false,
}

function vide(partiel: Partial<TableDetail> = {}): TableDetail {
  return { ...DETAIL, indexes: [], constraints: [], triggers: [], ...partiel }
}

function monter(ui: ReactElement) {
  return render(<LanguageProvider preferences={{ language: 'fr' }}>{ui}</LanguageProvider>)
}

describe('StructureView', () => {
  it('affiche les trois comptes de l’introspection', () => {
    monter(<StructureView detail={DETAIL} schema="public" />)
    expect(screen.getByText('4 colonnes')).toBeInTheDocument()
    expect(screen.getByText('2 index')).toBeInTheDocument()
    expect(screen.getByText('1 contrainte')).toBeInTheDocument()
  })

  it('nomme l’identité d’une clé primaire, que le catalogue laisse sans défaut', () => {
    monter(<StructureView detail={DETAIL} schema="public" />)
    const tableau = screen.getByRole('table', { name: /Colonnes de public\.orders/ })
    const ligne = within(tableau).getByText('id').closest('tr') as HTMLElement
    // Sans le champ `identity` de `06c`, cette cellule dirait « — » et se lirait comme une colonne
    // à remplir soi-même.
    expect(within(ligne).getByText('identity')).toBeInTheDocument()
  })

  it('donne la cible d’une clé étrangère, et la marque comme déduite', () => {
    monter(<StructureView detail={DETAIL} schema="public" />)
    const cible = screen.getByText('→ users.id')
    expect(cible).toHaveAttribute('title', 'déduit du catalogue par DoraBase')
  })

  it('nomme la clé pour les lecteurs d’écran, que l’icône seule ne dit pas', () => {
    monter(<StructureView detail={DETAIL} schema="public" />)
    expect(screen.getByText('clé primaire')).toBeInTheDocument()
    expect(screen.getByText('clé étrangère')).toBeInTheDocument()
  })

  it('filtre sur le type autant que sur le nom', async () => {
    const utilisateur = userEvent.setup()
    monter(<StructureView detail={DETAIL} schema="public" />)
    const champ = screen.getByRole('textbox', { name: /Filtrer les colonnes/ })

    await utilisateur.type(champ, 'timestamptz')

    const tableau = screen.getByRole('table', { name: /Colonnes de public\.orders/ })
    // On cherche « les colonnes en timestamptz » : un filtre qui ne porterait que sur le nom
    // répondrait « aucune colonne », ce qui est faux.
    expect(within(tableau).getByText('created_at')).toBeInTheDocument()
    expect(within(tableau).queryByText('note')).toBeNull()
  })

  it('résume les index, et l’unicité se lit — pas seulement se colore', () => {
    monter(<StructureView detail={DETAIL} schema="public" />)
    // L'unicité empêche des écritures : la coder par la seule teinte d'une icône la rendrait
    // invisible à la voix, et discutable à l'œil.
    expect(screen.getByText('unique btree(id)')).toBeInTheDocument()
    expect(screen.getByText('btree(created_at DESC)')).toBeInTheDocument()
  })

  it('dit ses vides plutôt que d’effacer ses sections', () => {
    monter(<StructureView detail={vide()} schema="public" />)
    // Une section absente se lit comme une donnée non chargée — le doute exact que le défaut de
    // `06d` a produit.
    expect(screen.getByText('Aucun index.')).toBeInTheDocument()
    expect(screen.getByText('Aucune contrainte, aucun déclencheur.')).toBeInTheDocument()
    // Et les comptes suivent : ils viennent de la même lecture.
    expect(screen.getByText('0 index')).toBeInTheDocument()
  })

  it('distingue une lecture en cours d’une absence de table', () => {
    const { unmount } = monter(<StructureView detail={null} schema="public" loading />)
    expect(screen.getByText('Lecture de la structure…')).toBeInTheDocument()
    unmount()
    monter(<StructureView detail={null} schema="public" />)
    expect(screen.getByText('Ouvrez une table pour en voir la structure.')).toBeInTheDocument()
  })
})

describe('resumeDIndex', () => {
  it('garde la méthode et les colonnes, jette le reste', () => {
    expect(
      resumeDIndex(
        'CREATE INDEX orders_user_status_idx ON public.orders USING btree (user_id, status)',
      ),
    ).toBe('btree(user_id,status)')
  })

  it('rend la définition entière quand elle ne suit pas la forme attendue', () => {
    // Un index d'exclusion ou une syntaxe qu'on n'a pas prévue : afficher la définition brute est
    // moins faux qu'un résumé inventé.
    expect(resumeDIndex('CREATE INDEX bizarre ON t (a) WHERE b')).toBe(
      'CREATE INDEX bizarre ON t (a) WHERE b',
    )
  })
})

describe('momentDuDeclencheur', () => {
  it('garde le moment et l’événement', () => {
    expect(
      momentDuDeclencheur(
        'CREATE TRIGGER t BEFORE INSERT OR UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION f()',
      ),
    ).toBe('before insert or update')
  })
})
