/* Généré par pnpm tokens:build — ne pas éditer */
/* biome-ignore-all format: fichier généré, mise en forme produite par le générateur */
export type TokenName =
  | 'accent'
  | 'accent-deep'
  | 'accent-deeper'
  | 'bar'
  | 'border'
  | 'border-dashed'
  | 'border-field'
  | 'btn-strong-bg'
  | 'btn-strong-ink'
  | 'canvas'
  | 'danger'
  | 'danger-bg'
  | 'danger-bg-2'
  | 'danger-ink'
  | 'danger-ink-2'
  | 'danger-ink-3'
  | 'dark'
  | 'dark-2'
  | 'disabled'
  | 'divider'
  | 'divider-2'
  | 'engine-bq'
  | 'engine-bq-bg'
  | 'engine-mg'
  | 'engine-mg-bg'
  | 'engine-my'
  | 'engine-my-bg'
  | 'engine-pg'
  | 'engine-pg-bg'
  | 'engine-rd'
  | 'engine-rd-bg'
  | 'engine-sf'
  | 'engine-sf-bg'
  | 'engine-sq'
  | 'engine-sq-bg'
  | 'field'
  | 'font-mono'
  | 'font-title'
  | 'font-ui'
  | 'gold'
  | 'gridline'
  | 'gridline-2'
  | 'h-bar'
  | 'h-btn-lg'
  | 'h-btn-md'
  | 'h-btn-sm'
  | 'h-btn-xl'
  | 'h-btn-xs'
  | 'h-field'
  | 'h-statusbar'
  | 'h-titlebar'
  | 'h-tree-row'
  | 'hero-wash'
  | 'hover-bg'
  | 'hover-border'
  | 'hover-close'
  | 'hover-close-ink'
  | 'hover-row'
  | 'info'
  | 'info-bg'
  | 'ink'
  | 'ink-2'
  | 'ink-3'
  | 'ink-4'
  | 'ink-5'
  | 'ink-6'
  | 'ink-7'
  | 'ink-8'
  | 'ink-meta'
  | 'ink-on-accent'
  | 'ink-on-dark'
  | 'json-key'
  | 'json-number'
  | 'json-punct'
  | 'json-string'
  | 'leading-code'
  | 'leading-code-tight'
  | 'leading-grid'
  | 'leading-ui'
  | 'link'
  | 'logo-plate'
  | 'muted'
  | 'on-dark'
  | 'paper'
  | 'paper-alt'
  | 'paper-bright'
  | 'preview-dark-bar'
  | 'preview-dark-paper'
  | 'preview-light-bar'
  | 'preview-light-paper'
  | 'radius-badge'
  | 'radius-badge-2'
  | 'radius-control'
  | 'radius-control-2'
  | 'radius-field'
  | 'radius-field-2'
  | 'radius-logo'
  | 'radius-panel'
  | 'radius-panel-2'
  | 'radius-panel-3'
  | 'radius-window'
  | 'rowh'
  | 'rowh-max'
  | 'rowh-min'
  | 'selected'
  | 'shadow-accent'
  | 'shadow-accent-2'
  | 'shadow-cell'
  | 'shadow-focus'
  | 'shadow-logo'
  | 'shadow-modal'
  | 'shadow-popover'
  | 'shadow-switch'
  | 'shadow-window'
  | 'space-1'
  | 'space-2'
  | 'space-3'
  | 'space-4'
  | 'space-5'
  | 'space-6'
  | 'space-7'
  | 'space-8'
  | 'success'
  | 'success-bg'
  | 'success-ink'
  | 'syn-comment'
  | 'syn-ident'
  | 'syn-keyword'
  | 'syn-linenum'
  | 'syn-number'
  | 'syn-string'
  | 'text-body'
  | 'text-caps'
  | 'text-caps-sm'
  | 'text-control'
  | 'text-dense'
  | 'text-hero'
  | 'text-label'
  | 'text-meta'
  | 'text-title'
  | 'text-wordmark'
  | 'track-off'
  | 'tracking-caps'
  | 'tracking-caps-sm'
  | 'veil'
  | 'veil-2'
  | 'violet'
  | 'violet-bg'
  | 'violet-ink'
  | 'warn'
  | 'warn-bg'
  | 'warn-bg-2'
  | 'warn-ink'
  | 'weight-black'
  | 'weight-bold'
  | 'weight-medium'
  | 'weight-normal'
  | 'weight-semibold'

export const tokens: Record<TokenName, string> = {
  'accent': 'var(--accent)',
  'accent-deep': 'var(--accent-deep)',
  'accent-deeper': 'var(--accent-deeper)',
  'bar': 'var(--bar)',
  'border': 'var(--border)',
  'border-dashed': 'var(--border-dashed)',
  'border-field': 'var(--border-field)',
  'btn-strong-bg': 'var(--btn-strong-bg)',
  'btn-strong-ink': 'var(--btn-strong-ink)',
  'canvas': 'var(--canvas)',
  'danger': 'var(--danger)',
  'danger-bg': 'var(--danger-bg)',
  'danger-bg-2': 'var(--danger-bg-2)',
  'danger-ink': 'var(--danger-ink)',
  'danger-ink-2': 'var(--danger-ink-2)',
  'danger-ink-3': 'var(--danger-ink-3)',
  'dark': 'var(--dark)',
  'dark-2': 'var(--dark-2)',
  'disabled': 'var(--disabled)',
  'divider': 'var(--divider)',
  'divider-2': 'var(--divider-2)',
  'engine-bq': 'var(--engine-bq)',
  'engine-bq-bg': 'var(--engine-bq-bg)',
  'engine-mg': 'var(--engine-mg)',
  'engine-mg-bg': 'var(--engine-mg-bg)',
  'engine-my': 'var(--engine-my)',
  'engine-my-bg': 'var(--engine-my-bg)',
  'engine-pg': 'var(--engine-pg)',
  'engine-pg-bg': 'var(--engine-pg-bg)',
  'engine-rd': 'var(--engine-rd)',
  'engine-rd-bg': 'var(--engine-rd-bg)',
  'engine-sf': 'var(--engine-sf)',
  'engine-sf-bg': 'var(--engine-sf-bg)',
  'engine-sq': 'var(--engine-sq)',
  'engine-sq-bg': 'var(--engine-sq-bg)',
  'field': 'var(--field)',
  'font-mono': 'var(--font-mono)',
  'font-title': 'var(--font-title)',
  'font-ui': 'var(--font-ui)',
  'gold': 'var(--gold)',
  'gridline': 'var(--gridline)',
  'gridline-2': 'var(--gridline-2)',
  'h-bar': 'var(--h-bar)',
  'h-btn-lg': 'var(--h-btn-lg)',
  'h-btn-md': 'var(--h-btn-md)',
  'h-btn-sm': 'var(--h-btn-sm)',
  'h-btn-xl': 'var(--h-btn-xl)',
  'h-btn-xs': 'var(--h-btn-xs)',
  'h-field': 'var(--h-field)',
  'h-statusbar': 'var(--h-statusbar)',
  'h-titlebar': 'var(--h-titlebar)',
  'h-tree-row': 'var(--h-tree-row)',
  'hero-wash': 'var(--hero-wash)',
  'hover-bg': 'var(--hover-bg)',
  'hover-border': 'var(--hover-border)',
  'hover-close': 'var(--hover-close)',
  'hover-close-ink': 'var(--hover-close-ink)',
  'hover-row': 'var(--hover-row)',
  'info': 'var(--info)',
  'info-bg': 'var(--info-bg)',
  'ink': 'var(--ink)',
  'ink-2': 'var(--ink-2)',
  'ink-3': 'var(--ink-3)',
  'ink-4': 'var(--ink-4)',
  'ink-5': 'var(--ink-5)',
  'ink-6': 'var(--ink-6)',
  'ink-7': 'var(--ink-7)',
  'ink-8': 'var(--ink-8)',
  'ink-meta': 'var(--ink-meta)',
  'ink-on-accent': 'var(--ink-on-accent)',
  'ink-on-dark': 'var(--ink-on-dark)',
  'json-key': 'var(--json-key)',
  'json-number': 'var(--json-number)',
  'json-punct': 'var(--json-punct)',
  'json-string': 'var(--json-string)',
  'leading-code': 'var(--leading-code)',
  'leading-code-tight': 'var(--leading-code-tight)',
  'leading-grid': 'var(--leading-grid)',
  'leading-ui': 'var(--leading-ui)',
  'link': 'var(--link)',
  'logo-plate': 'var(--logo-plate)',
  'muted': 'var(--muted)',
  'on-dark': 'var(--on-dark)',
  'paper': 'var(--paper)',
  'paper-alt': 'var(--paper-alt)',
  'paper-bright': 'var(--paper-bright)',
  'preview-dark-bar': 'var(--preview-dark-bar)',
  'preview-dark-paper': 'var(--preview-dark-paper)',
  'preview-light-bar': 'var(--preview-light-bar)',
  'preview-light-paper': 'var(--preview-light-paper)',
  'radius-badge': 'var(--radius-badge)',
  'radius-badge-2': 'var(--radius-badge-2)',
  'radius-control': 'var(--radius-control)',
  'radius-control-2': 'var(--radius-control-2)',
  'radius-field': 'var(--radius-field)',
  'radius-field-2': 'var(--radius-field-2)',
  'radius-logo': 'var(--radius-logo)',
  'radius-panel': 'var(--radius-panel)',
  'radius-panel-2': 'var(--radius-panel-2)',
  'radius-panel-3': 'var(--radius-panel-3)',
  'radius-window': 'var(--radius-window)',
  'rowh': 'var(--rowh)',
  'rowh-max': 'var(--rowh-max)',
  'rowh-min': 'var(--rowh-min)',
  'selected': 'var(--selected)',
  'shadow-accent': 'var(--shadow-accent)',
  'shadow-accent-2': 'var(--shadow-accent-2)',
  'shadow-cell': 'var(--shadow-cell)',
  'shadow-focus': 'var(--shadow-focus)',
  'shadow-logo': 'var(--shadow-logo)',
  'shadow-modal': 'var(--shadow-modal)',
  'shadow-popover': 'var(--shadow-popover)',
  'shadow-switch': 'var(--shadow-switch)',
  'shadow-window': 'var(--shadow-window)',
  'space-1': 'var(--space-1)',
  'space-2': 'var(--space-2)',
  'space-3': 'var(--space-3)',
  'space-4': 'var(--space-4)',
  'space-5': 'var(--space-5)',
  'space-6': 'var(--space-6)',
  'space-7': 'var(--space-7)',
  'space-8': 'var(--space-8)',
  'success': 'var(--success)',
  'success-bg': 'var(--success-bg)',
  'success-ink': 'var(--success-ink)',
  'syn-comment': 'var(--syn-comment)',
  'syn-ident': 'var(--syn-ident)',
  'syn-keyword': 'var(--syn-keyword)',
  'syn-linenum': 'var(--syn-linenum)',
  'syn-number': 'var(--syn-number)',
  'syn-string': 'var(--syn-string)',
  'text-body': 'var(--text-body)',
  'text-caps': 'var(--text-caps)',
  'text-caps-sm': 'var(--text-caps-sm)',
  'text-control': 'var(--text-control)',
  'text-dense': 'var(--text-dense)',
  'text-hero': 'var(--text-hero)',
  'text-label': 'var(--text-label)',
  'text-meta': 'var(--text-meta)',
  'text-title': 'var(--text-title)',
  'text-wordmark': 'var(--text-wordmark)',
  'track-off': 'var(--track-off)',
  'tracking-caps': 'var(--tracking-caps)',
  'tracking-caps-sm': 'var(--tracking-caps-sm)',
  'veil': 'var(--veil)',
  'veil-2': 'var(--veil-2)',
  'violet': 'var(--violet)',
  'violet-bg': 'var(--violet-bg)',
  'violet-ink': 'var(--violet-ink)',
  'warn': 'var(--warn)',
  'warn-bg': 'var(--warn-bg)',
  'warn-bg-2': 'var(--warn-bg-2)',
  'warn-ink': 'var(--warn-ink)',
  'weight-black': 'var(--weight-black)',
  'weight-bold': 'var(--weight-bold)',
  'weight-medium': 'var(--weight-medium)',
  'weight-normal': 'var(--weight-normal)',
  'weight-semibold': 'var(--weight-semibold)',
}
